/**
 * Strategy service — formatting layer on top of optimizer output.
 *
 * These functions are PURE: they take an OptimizationResult and produce
 * human-readable strategy/cheatsheet objects. No DB calls, no side-effects.
 * The optimizer logic is never duplicated here.
 *
 * Pipeline:
 *   optimize()  →  generateCardStackStrategy()  →  generateCheatsheet()
 */
import type {
  OptimizationResult,
  CategoryOptimization,
  CardStackStrategy,
  StrategyItem,
  Cheatsheet,
} from '../../types';

// ─── Shared labels (mirrors optimizer.service constants) ──────────────────────

const CATEGORY_LABELS: Record<string, string> = {
  groceries: 'Groceries',
  dining: 'Dining',
  travel: 'Travel',
  online: 'Online Shopping',
  fuel: 'Fuel',
  utility: 'Utilities',
};

const CATEGORY_EMOJI: Record<string, string> = {
  groceries: '🛒',
  dining: '🍽️',
  travel: '✈️',
  online: '🛍️',
  fuel: '⛽',
  utility: '💡',
};

// ─── Reason builder ───────────────────────────────────────────────────────────
//
// Produces a one-line human explanation of why a card was chosen for a category.
// Rate tiers mirror the "sub-optimal < 2%" threshold already used in generateTips.

function buildReason(category: string, opt: CategoryOptimization): string {
  const label = (CATEGORY_LABELS[category] ?? category).toLowerCase();
  const base = `${opt.rate}% on ${label}`;

  if (opt.rate >= 10) return `${base} — exceptional rate, best in class`;
  if (opt.rate >= 5)  return `${base} — strong category-specific rate`;
  if (opt.rate >= 3)  return `${base} — competitive rate in your card stack`;
  if (opt.rate >= 2)  return `${base} — solid baseline across your cards`;
  return `${base} — best available in your current stack`;
}

// ─── generateCardStackStrategy ────────────────────────────────────────────────
//
// Converts the optimizer's bestPerCategory map into an ordered, annotated
// strategy that is easy to display in a UI or send to the user.
//
// Deduplicates cards for the totalCardsUsed count — a card that covers three
// categories still counts as one card in the wallet.

export function generateCardStackStrategy(
  optimizerOutput: OptimizationResult
): CardStackStrategy {
  const { bestPerCategory, totalOptimizedAnnualRewards, tips } = optimizerOutput;

  const usedCardSlugs = new Set<string>();
  const strategy: StrategyItem[] = [];

  for (const [category, opt] of Object.entries(bestPerCategory)) {
    usedCardSlugs.add(opt.card.slug);

    strategy.push({
      category,
      label: `Best for ${CATEGORY_LABELS[category] ?? category}`,
      card: opt.card.name,
      bank: opt.card.bank,
      rewardRate: opt.rate,
      reason: buildReason(category, opt),
      annualReward: opt.annualReward,
    });
  }

  // Sort by annual reward value descending — biggest wins appear first
  strategy.sort((a, b) => b.annualReward - a.annualReward);

  return {
    totalCardsUsed: usedCardSlugs.size,
    strategy,
    annualRewards: totalOptimizedAnnualRewards,
    tips,
  };
}

// ─── generateCheatsheet ───────────────────────────────────────────────────────
//
// Produces a wallet-ready cheatsheet from a strategy.
//
// The `text` field is a printable plain-text version — suitable for copy-paste,
// share via WhatsApp, or rendering as a pre-formatted download.

export function generateCheatsheet(strategy: CardStackStrategy): Cheatsheet {
  const title = 'Your Swipe Strategy';
  const summary = `${strategy.totalCardsUsed} card${strategy.totalCardsUsed === 1 ? '' : 's'} · ₹${strategy.annualRewards.toLocaleString('en-IN')}/year in rewards`;

  // One line per category: "✈️  Travel → Axis Atlas (5%)"
  const items = strategy.strategy.map((s) => {
    const emoji = CATEGORY_EMOJI[s.category] ?? '💳';
    const label = CATEGORY_LABELS[s.category] ?? s.category;
    return `${emoji}  ${label} → ${s.card} (${s.rewardRate}%)`;
  });

  // Plain-text version — printable / shareable
  const divider = '─'.repeat(40);
  const textLines: string[] = [
    '╔══════════════════════════════════════╗',
    '║       YOUR SWIPE STRATEGY            ║',
    '╚══════════════════════════════════════╝',
    '',
    `  ${summary}`,
    '',
    divider,
    '  WHICH CARD TO SWIPE',
    divider,
    '',
    ...items.map((item) => `  ${item}`),
    '',
    divider,
    '  TIPS',
    divider,
    '',
    ...strategy.tips.map((tip) => `  • ${tip}`),
    '',
    divider,
    '  Generated by SwipeSmart · swipesmart.in',
    divider,
  ];

  return {
    title,
    summary,
    items,
    text: textLines.join('\n'),
  };
}
