/**
 * Seed file — all 36 cards verified against official bank sources, March 2026.
 * Reward rates = effective % value-back after point redemption conversions.
 * Run with: npm run db:seed
 */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const CARDS = [
  // ─── HDFC Bank ────────────────────────────────────────────────────────────
  {
    slug: 'hdfc_regalia',
    name: 'Regalia Gold',
    bank: 'HDFC Bank',
    network: 'Visa',
    annualFee: 2500,
    feeWaiverRule: 'Waived on ₹4L annual spend',
    minIncome: 100000,
    rewardRates: { travel: 5, dining: 2.7, online: 2.7, groceries: 2.7, fuel: 0, utility: 2.7, default: 2.7 },
    perks: [
      '12 domestic lounge visits/yr (3/qtr)',
      '6 intl lounge visits/yr via Priority Pass',
      '5X rewards on Myntra/Nykaa/M&S/Reliance Digital',
      '₹5k flight voucher milestone at ₹5L annual spend',
    ],
    bestFor: ['travel_perks', 'rewards_points'],
    categories: ['travel', 'online'],
    intlTravel: true,
    welcomeBonus: 2500,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'hdfc_millennia',
    name: 'Millennia',
    bank: 'HDFC Bank',
    network: 'Visa',
    annualFee: 1000,
    feeWaiverRule: 'Waived on ₹1L annual spend',
    minIncome: 35000,
    rewardRates: { travel: 1.5, dining: 5, online: 5, groceries: 1.5, fuel: 0, utility: 1.5, default: 1.5 },
    perks: [
      '5% cashback on Amazon/Flipkart/Zomato/Swiggy/Uber & 7 more brands (cap ₹1k/mo)',
      '1.5% on all other eligible spends',
      '₹1k gift voucher on ₹1L quarterly spend',
      '1% fuel surcharge waiver',
    ],
    bestFor: ['cashback', 'online'],
    categories: ['online', 'dining'],
    intlTravel: false,
    welcomeBonus: 1000,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'hdfc_infinia',
    name: 'Infinia Metal',
    bank: 'HDFC Bank',
    network: 'Visa',
    annualFee: 12500,
    feeWaiverRule: 'Waived on ₹10L annual spend',
    minIncome: 300000,
    rewardRates: { travel: 3.33, dining: 3.33, online: 3.33, groceries: 3.33, fuel: 1, utility: 3.33, default: 3.33 },
    perks: [
      'Unlimited domestic + intl lounge (Priority Pass)',
      '5 pts/₹150 base = 3.33% (1pt=₹1 via SmartBuy travel)',
      '10X on SmartBuy travel/shopping (up to 15k pts/month)',
      'Unlimited golf + Club Marriott + ITC 3-night/2-pay',
      'Invite-only: needs ₹5L monthly salary or ₹8L existing HDFC limit',
    ],
    bestFor: ['travel_perks', 'rewards_points'],
    categories: ['travel', 'online', 'dining'],
    intlTravel: true,
    welcomeBonus: 12500,
    isActive: true,
    isInviteOnly: true,
  },
  {
    slug: 'hdfc_tata_neu',
    name: 'Tata Neu Infinity',
    bank: 'HDFC Bank',
    network: 'Visa',
    annualFee: 1499,
    feeWaiverRule: 'Waived on ₹3L annual spend',
    minIncome: 100000,
    rewardRates: { travel: 5, dining: 1.5, online: 5, groceries: 5, fuel: 0, utility: 1.5, default: 1.5 },
    perks: [
      '5–10% NeuCoins on Tata brands (Air India, BigBasket, Croma, Westside)',
      '1.5% on all other spends',
      '8 domestic + 4 intl lounge visits/yr',
      '₹10k Tata CLiQ welcome voucher',
      'NeuCoins validity: 12 months from credit date (from Aug 2025)',
    ],
    bestFor: ['cashback', 'online'],
    categories: ['online', 'groceries', 'travel'],
    intlTravel: true,
    welcomeBonus: 1499,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'hdfc_diners_black',
    name: 'Diners Club Black',
    bank: 'HDFC Bank',
    network: 'Diners',
    annualFee: 10000,
    feeWaiverRule: 'Waived on ₹5L annual spend',
    minIncome: 250000,
    rewardRates: { travel: 3.33, dining: 3.33, online: 3.33, groceries: 3.33, fuel: 1, utility: 3.33, default: 3.33 },
    perks: [
      '5 pts/₹150 base = 3.33% (1pt=₹1 SmartBuy)',
      '10X SmartBuy travel/shopping (15k pts/month cap)',
      'Unlimited domestic + 6 intl lounge visits/yr',
      'Amazon Prime + Swiggy One membership welcome',
      '10k bonus pts quarterly on ₹4L spend milestone',
    ],
    bestFor: ['travel_perks', 'rewards_points'],
    categories: ['travel', 'dining', 'online'],
    intlTravel: true,
    welcomeBonus: 10000,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'hdfc_swiggy',
    name: 'Swiggy HDFC Bank',
    bank: 'HDFC Bank',
    network: 'Visa',
    annualFee: 500,
    feeWaiverRule: 'Waived on ₹2L annual spend',
    minIncome: 25000,
    rewardRates: { travel: 1, dining: 10, online: 5, groceries: 5, fuel: 0, utility: 1, default: 1 },
    perks: [
      '10% cashback on Swiggy (food, Instamart, Dineout) — capped ₹1,500/month',
      '5% on all online spends across all merchants — capped ₹1,500/month',
      '1% on all other spends — uncapped',
      'Complimentary 3-month Swiggy One membership',
    ],
    bestFor: ['cashback', 'dining'],
    categories: ['dining', 'online'],
    intlTravel: false,
    welcomeBonus: 500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Axis Bank ────────────────────────────────────────────────────────────
  {
    slug: 'axis_atlas',
    name: 'Atlas',
    bank: 'Axis Bank',
    network: 'Visa',
    annualFee: 5000,
    feeWaiverRule: 'No spend waiver — renewal EDGE Miles bonus instead',
    minIncome: 150000,
    rewardRates: { travel: 5, dining: 2, online: 2, groceries: 2, fuel: 0, utility: 0, default: 2 },
    perks: [
      '5 EDGE Miles/₹100 on direct airline/hotel & TravelEDGE portal',
      '2 EDGE Miles/₹100 on all other eligible spends',
      '1:2 transfer to 20+ airline & hotel partners',
      'Tier-based lounge access (Silver/Gold/Platinum)',
    ],
    bestFor: ['travel_perks'],
    categories: ['travel'],
    intlTravel: true,
    welcomeBonus: 2500,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'axis_ace',
    name: 'Ace',
    bank: 'Axis Bank',
    network: 'Visa',
    annualFee: 499,
    feeWaiverRule: 'Waived on ₹2L annual spend',
    minIncome: 25000,
    rewardRates: { travel: 1.5, dining: 4, online: 1.5, groceries: 1.5, fuel: 0, utility: 5, default: 1.5 },
    perks: [
      '5% cashback on utility bills via Google Pay (Android only)',
      '4% cashback on Zomato, Swiggy & Ola (₹500 combined cap/mo)',
      '1.5% on all other eligible spends — uncapped',
      '4 domestic lounge visits/yr',
    ],
    bestFor: ['cashback', 'low_fee'],
    categories: ['utility', 'dining'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'axis_magnus',
    name: 'Magnus',
    bank: 'Axis Bank',
    network: 'Visa',
    annualFee: 10000,
    feeWaiverRule: 'Waived on ₹15L annual spend',
    minIncome: 150000,
    rewardRates: { travel: 9, dining: 3, online: 3, groceries: 3, fuel: 0, utility: 0, default: 3 },
    perks: [
      '12 EDGE pts/₹200 base = 3% (up to ₹1.5L/month)',
      '35 EDGE pts/₹200 on spends above ₹1.5L = ~8.75%',
      '60 EDGE pts/₹200 on TravelEDGE portal bookings',
      'Tier-based lounge access (Silver/Gold/Platinum)',
      'Transfer to 20+ airline & hotel partners at 1:1',
    ],
    bestFor: ['travel_perks', 'rewards_points'],
    categories: ['travel', 'online'],
    intlTravel: true,
    welcomeBonus: 10000,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'axis_flipkart',
    name: 'Flipkart Axis',
    bank: 'Axis Bank',
    network: 'Visa',
    annualFee: 500,
    feeWaiverRule: 'Often issued as Lifetime Free',
    minIncome: 20000,
    rewardRates: { travel: 1.5, dining: 4, online: 5, groceries: 1.5, fuel: 0, utility: 1.5, default: 1.5 },
    perks: [
      '5% cashback on Flipkart & Cleartrip (capped ₹4,000/qtr each from June 2025)',
      '7.5% cashback on Myntra (capped ₹4,000/qtr)',
      '4% on Swiggy & Uber (capped ₹500/month combined)',
      'No lounge access (discontinued July 2025)',
    ],
    bestFor: ['cashback', 'online', 'low_fee'],
    categories: ['online', 'dining'],
    intlTravel: false,
    welcomeBonus: 500,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'axis_magnus_burgundy',
    name: 'Magnus for Burgundy',
    bank: 'Axis Bank',
    network: 'Visa',
    annualFee: 0,
    feeWaiverRule: 'Free for Axis Burgundy account holders (₹10L AMB required)',
    minIncome: 300000,
    rewardRates: { travel: 9, dining: 3, online: 3, groceries: 3, fuel: 0, utility: 0, default: 3 },
    perks: [
      'Free card with Axis Burgundy account (₹10L average monthly balance)',
      '12 EDGE pts/₹200 base = 3% on eligible spends up to ₹1.5L/month',
      '35 EDGE pts/₹200 on incremental spends above ₹1.5L/month',
      '60 EDGE pts/₹200 on TravelEDGE portal — among highest travel return cards',
      'Transfer to 20+ partners; top card for HNI travel optimizers',
    ],
    bestFor: ['travel_perks', 'rewards_points'],
    categories: ['travel', 'online'],
    intlTravel: true,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'axis_myzone',
    name: 'My Zone',
    bank: 'Axis Bank',
    network: 'Visa',
    annualFee: 500,
    feeWaiverRule: 'Often issued Lifetime Free via select channels',
    minIncome: 15000,
    rewardRates: { travel: 0, dining: 0.5, online: 0.5, groceries: 0, fuel: 0, utility: 0, default: 0.5 },
    perks: [
      'Buy 1 Get 1 movie ticket via District app — capped ₹200/month',
      '₹120 off on Swiggy food orders — 2x/month (min ₹500 order)',
      'Complimentary SonyLIV Premium membership (yr 1 on joining)',
      '1 domestic lounge visit/qtr — requires ₹50k spend in previous 3 months',
    ],
    bestFor: ['low_fee'],
    categories: ['dining', 'online'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'axis_privilege',
    name: 'Privilege',
    bank: 'Axis Bank',
    network: 'Visa',
    annualFee: 1500,
    feeWaiverRule: 'Waived on ₹5L annual spend',
    minIncome: 50000,
    rewardRates: { travel: 1, dining: 1, online: 1, groceries: 1, fuel: 0, utility: 0, default: 1 },
    perks: [
      '10 EDGE pts/₹200 on all eligible domestic & intl spends = 1% effective',
      '12,500 welcome EDGE pts = ₹2,500 value on 1st spend within 30 days',
      '8 domestic lounge visits/yr',
      'BOGO movie via District app — capped ₹250/month',
      'Up to ₹800 off dining via EazyDiner — once/month',
    ],
    bestFor: ['rewards_points'],
    categories: ['online', 'dining', 'travel'],
    intlTravel: false,
    welcomeBonus: 2500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── SBI Card ─────────────────────────────────────────────────────────────
  {
    slug: 'sbi_simplyclick',
    name: 'SimplyCLICK',
    bank: 'SBI Card',
    network: 'Visa',
    annualFee: 499,
    feeWaiverRule: 'Waived on ₹1L annual spend',
    minIncome: 20000,
    rewardRates: { travel: 1.25, dining: 1.25, online: 2.5, groceries: 0.25, fuel: 0, utility: 0, default: 0.25 },
    perks: [
      '10X points on Myntra/BookMyShow/Cleartrip/Apollo & partners = 2.5% value',
      '5X on all other online spends = 1.25%',
      '₹2k Cleartrip/Yatra e-voucher at ₹1L & ₹2L milestones',
      'No lounge access on this card',
    ],
    bestFor: ['online', 'low_fee'],
    categories: ['online'],
    intlTravel: false,
    welcomeBonus: 500,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'sbi_elite',
    name: 'Elite',
    bank: 'SBI Card',
    network: 'Mastercard',
    annualFee: 4999,
    feeWaiverRule: 'Waived on ₹10L annual spend',
    minIncome: 60000,
    rewardRates: { travel: 0.25, dining: 1.25, online: 0.25, groceries: 1.25, fuel: 0, utility: 0.25, default: 0.25 },
    perks: [
      '2 free BookMyShow movie tickets/month worth ₹6k/yr',
      '8 domestic + 6 intl lounge visits/yr',
      '5X rewards on dining, grocery & departmental stores',
      '₹5k welcome voucher + Club ITC Silver membership',
    ],
    bestFor: ['travel_perks'],
    categories: ['dining', 'groceries'],
    intlTravel: true,
    welcomeBonus: 5000,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'sbi_cashback',
    name: 'Cashback SBI',
    bank: 'SBI Card',
    network: 'Visa',
    annualFee: 999,
    feeWaiverRule: 'Waived on ₹2L annual spend',
    minIncome: 20000,
    rewardRates: { travel: 5, dining: 5, online: 5, groceries: 5, fuel: 0, utility: 0, default: 1 },
    perks: [
      '5% cashback on ALL online spends — no merchant restriction (cap ₹2k/month from Apr 2026)',
      '1% cashback on all offline spends',
      'Auto-credited to statement within 2 days',
      'Exclusions: fuel, utility, insurance, rent, wallets',
    ],
    bestFor: ['cashback', 'online'],
    categories: ['online', 'dining', 'travel'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'sbi_aurum',
    name: 'Aurum',
    bank: 'SBI Card',
    network: 'Mastercard',
    annualFee: 9999,
    feeWaiverRule: 'Annual fee offset by ₹3k quarterly voucher benefit',
    minIncome: 175000,
    rewardRates: { travel: 2, dining: 2, online: 2, groceries: 2, fuel: 0, utility: 2, default: 2 },
    perks: [
      '₹3,000 quarterly benefits (OTT subscriptions + vouchers) = ₹12k/yr value',
      'Unlimited domestic + 8 intl lounge visits/yr',
      '2% effective reward rate on all eligible spends',
      'Taj Epicure + Club ITC membership',
      'Golf privileges + concierge',
    ],
    bestFor: ['travel_perks', 'rewards_points'],
    categories: ['travel', 'dining'],
    intlTravel: true,
    welcomeBonus: 9999,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── American Express ─────────────────────────────────────────────────────
  {
    slug: 'amex_gold',
    name: 'Gold Charge Card',
    bank: 'American Express',
    network: 'Amex',
    annualFee: 1000,
    feeWaiverRule: 'Joining ₹1k (yr 1); renewal ₹4,500+GST from yr 2',
    minIncome: 60000,
    rewardRates: { travel: 1.4, dining: 1.4, online: 1.4, groceries: 1.4, fuel: 0, utility: 1.4, default: 1.4 },
    perks: [
      '1 MR point per ₹50 on all spends (~2% base)',
      '1,000 bonus MR points/month on 6 txns of ₹1k+ each',
      '5X via Amex Reward Multiplier portal',
      'Gold Collection: Taj/Amazon/Flipkart vouchers at 18K & 24K MR thresholds',
    ],
    bestFor: ['rewards_points'],
    categories: ['online', 'dining'],
    intlTravel: false,
    welcomeBonus: 1000,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'amex_plat_travel',
    name: 'Platinum Travel',
    bank: 'American Express',
    network: 'Amex',
    annualFee: 3500,
    feeWaiverRule: 'No spend-based waiver',
    minIncome: 100000,
    rewardRates: { travel: 2, dining: 2, online: 2, groceries: 2, fuel: 0, utility: 2, default: 2 },
    perks: [
      'Milestone IndiGo vouchers worth up to ₹11,800/yr',
      '4 domestic lounge visits/qtr (16/yr) via Visa',
      '1 MR point per ₹50 on all eligible spends',
      'Lower joining fee vs Gold Charge Card',
    ],
    bestFor: ['travel_perks', 'rewards_points'],
    categories: ['travel', 'dining'],
    intlTravel: true,
    welcomeBonus: 3500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── ICICI Bank ───────────────────────────────────────────────────────────
  {
    slug: 'icici_amazon',
    name: 'Amazon Pay ICICI',
    bank: 'ICICI Bank',
    network: 'Visa',
    annualFee: 0,
    feeWaiverRule: 'Lifetime free — no annual fee ever',
    minIncome: 20000,
    rewardRates: { travel: 5, dining: 2, online: 5, groceries: 2, fuel: 0, utility: 0, default: 1 },
    perks: [
      '5% cashback on Amazon.in for Prime members (3% non-Prime)',
      '2% on 100+ Amazon Pay partner merchants',
      '1% on all other eligible spends — uncapped, no expiry',
      'No joining or annual fee ever',
    ],
    bestFor: ['cashback', 'low_fee', 'online'],
    categories: ['online', 'travel'],
    intlTravel: false,
    welcomeBonus: 200,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'icici_sapphire',
    name: 'Sapphiro',
    bank: 'ICICI Bank',
    network: 'Visa',
    annualFee: 3500,
    feeWaiverRule: 'Waived on ₹6L annual spend',
    minIncome: 80000,
    rewardRates: { travel: 2, dining: 2, online: 2, groceries: 2, fuel: 0, utility: 2, default: 2 },
    perks: [
      'Unlimited domestic + intl lounge access',
      '2% rewards on all eligible categories',
      '12X rewards on hotel bookings via ICICI iShop portal',
      'Complimentary golf rounds on ₹6L+ annual spend',
    ],
    bestFor: ['travel_perks', 'rewards_points'],
    categories: ['travel', 'dining'],
    intlTravel: true,
    welcomeBonus: 3500,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'icici_emeralde',
    name: 'Emeralde',
    bank: 'ICICI Bank',
    network: 'Visa',
    annualFee: 12000,
    feeWaiverRule: 'Waived on ₹15L annual spend',
    minIncome: 200000,
    rewardRates: { travel: 3, dining: 3, online: 3, groceries: 3, fuel: 0, utility: 3, default: 3 },
    perks: [
      '6 pts/₹200 base = 3% on all eligible spends',
      'Unlimited domestic + intl lounge access',
      'Complimentary golf + concierge services',
      'Travel insurance + 0% forex on select transactions',
      'Invite-based for premium customers',
    ],
    bestFor: ['travel_perks', 'rewards_points'],
    categories: ['travel', 'dining', 'online'],
    intlTravel: true,
    welcomeBonus: 12000,
    isActive: true,
    isInviteOnly: true,
  },

  // ─── Kotak Mahindra Bank ──────────────────────────────────────────────────
  {
    slug: 'kotak_811',
    name: '811 #DreamDifferent',
    bank: 'Kotak Mahindra Bank',
    network: 'Visa',
    annualFee: 0,
    feeWaiverRule: 'Lifetime free (secured against FD — no income proof needed)',
    minIncome: 0,
    rewardRates: { travel: 0.2, dining: 0.2, online: 0.8, groceries: 0.2, fuel: 0, utility: 0.2, default: 0.2 },
    perks: [
      'Best first card — no income proof, secured against Fixed Deposit',
      '4 pts/₹100 online = 0.8% value (1pt=₹0.20)',
      '₹1k milestone voucher on ₹72k annual spend',
      '1% fuel surcharge waiver',
    ],
    bestFor: ['low_fee'],
    categories: ['online'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'kotak_league',
    name: 'League Platinum',
    bank: 'Kotak Mahindra Bank',
    network: 'Visa',
    annualFee: 499,
    feeWaiverRule: 'Waived on ₹50k annual spend',
    minIncome: 25000,
    rewardRates: { travel: 0.67, dining: 1.33, online: 1.33, groceries: 0.67, fuel: 0, utility: 0.67, default: 0.67 },
    perks: [
      'Up to 8 pts/₹150 on select categories = 1.33% value',
      '3 free PVR tickets/yr on ₹75k annual spend',
      '4 domestic lounge visits/yr',
      '1% fuel surcharge waiver',
    ],
    bestFor: ['low_fee', 'rewards_points'],
    categories: ['dining', 'online'],
    intlTravel: false,
    welcomeBonus: 500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── HSBC Bank ────────────────────────────────────────────────────────────
  {
    slug: 'hsbc_live_plus',
    name: 'Live+',
    bank: 'HSBC Bank',
    network: 'Visa',
    annualFee: 999,
    feeWaiverRule: 'Waived on ₹2L annual spend',
    minIncome: 25000,
    rewardRates: { travel: 1.5, dining: 10, online: 1.5, groceries: 10, fuel: 0, utility: 1.5, default: 1.5 },
    perks: [
      '10% cashback on dining, groceries & food delivery — capped ₹1,000/month total',
      '1.5% unlimited cashback on all other eligible spends',
      'No merchant restrictions on base 1.5% rate',
      'Simple statement credit — no points to track',
    ],
    bestFor: ['cashback'],
    categories: ['dining', 'groceries'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'hsbc_cashback',
    name: 'Cashback',
    bank: 'HSBC Bank',
    network: 'Visa',
    annualFee: 750,
    feeWaiverRule: 'Waived on ₹1L annual spend',
    minIncome: 25000,
    rewardRates: { travel: 1.5, dining: 1.5, online: 1.5, groceries: 1.5, fuel: 1.5, utility: 1.5, default: 1.5 },
    perks: [
      'Flat 1.5% unlimited cashback on ALL eligible spends — no exclusions',
      'No merchant or category restrictions on base rate',
      'Simple, predictable rewards — no points to manage',
      'Low annual fee with easy waiver',
    ],
    bestFor: ['cashback', 'low_fee'],
    categories: ['online', 'dining', 'groceries', 'utility'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── IDFC First Bank ──────────────────────────────────────────────────────
  {
    slug: 'idfc_wealth',
    name: 'First Wealth',
    bank: 'IDFC First Bank',
    network: 'Visa',
    annualFee: 0,
    feeWaiverRule: 'Lifetime free — no annual fee ever',
    minIncome: 25000,
    rewardRates: { travel: 0.5, dining: 0.5, online: 0.5, groceries: 0.5, fuel: 0, utility: 0.5, default: 0.5 },
    perks: [
      'Lifetime free with premium perks',
      '0.5% on spends ≤₹20k/month; 1.66% above ₹20k/month',
      '8 domestic + 8 intl lounge visits/yr (requires ₹20k prev-month spend)',
      '2 free golf rounds/month, BOGO movie tickets',
      '1.5% forex markup — among lowest in India',
    ],
    bestFor: ['low_fee', 'travel_perks'],
    categories: ['travel', 'online'],
    intlTravel: true,
    welcomeBonus: 500,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'idfc_select',
    name: 'First Select',
    bank: 'IDFC First Bank',
    network: 'Visa',
    annualFee: 0,
    feeWaiverRule: 'Lifetime free',
    minIncome: 12000,
    rewardRates: { travel: 1.5, dining: 1.5, online: 1.5, groceries: 1.5, fuel: 0, utility: 1.5, default: 0.5 },
    perks: [
      'Lifetime free — no annual fee ever',
      '3pts/₹150 on spends up to ₹20k/month = ~0.5% base',
      '10pts/₹150 on spends above ₹20k/month = ~1.66%',
      'Points never expire',
      '4 domestic lounge + railway lounge visits/qtr',
    ],
    bestFor: ['low_fee'],
    categories: ['online', 'dining'],
    intlTravel: false,
    welcomeBonus: 500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Standard Chartered ───────────────────────────────────────────────────
  {
    slug: 'sc_ultimate',
    name: 'Ultimate',
    bank: 'Standard Chartered',
    network: 'Visa',
    annualFee: 5000,
    feeWaiverRule: 'No spend-based waiver',
    minIncome: 100000,
    rewardRates: { travel: 3.3, dining: 5, online: 3.3, groceries: 3.3, fuel: 1, utility: 3.3, default: 3.3 },
    perks: [
      '3.3 pts/₹100 on all eligible spends (1pt=₹1) = 3.3% base',
      '5% on dining at partner restaurants',
      'Unlimited domestic lounge + 4 intl visits/yr',
      'Low forex markup: 2%',
      'Golf privileges + travel insurance',
    ],
    bestFor: ['travel_perks', 'rewards_points'],
    categories: ['travel', 'dining', 'online'],
    intlTravel: true,
    welcomeBonus: 5000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── RBL Bank ─────────────────────────────────────────────────────────────
  {
    slug: 'rbl_world_safari',
    name: 'World Safari',
    bank: 'RBL Bank',
    network: 'Mastercard',
    annualFee: 3000,
    feeWaiverRule: 'Waived on ₹3L annual spend',
    minIncome: 50000,
    rewardRates: { travel: 3, dining: 2, online: 2, groceries: 2, fuel: 0, utility: 2, default: 2 },
    perks: [
      'ZERO forex markup — best card for international spends',
      '3% rewards on all travel spends',
      'Lounge access conditional on ₹5k prev-month spend (from July 2025)',
      'Golf rounds + travel insurance',
    ],
    bestFor: ['travel_perks'],
    categories: ['travel'],
    intlTravel: true,
    welcomeBonus: 3000,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'rbl_world_prime',
    name: 'World Prime SuperCard',
    bank: 'RBL Bank',
    network: 'Mastercard',
    annualFee: 2999,
    feeWaiverRule: 'No spend-based waiver',
    minIncome: 40000,
    rewardRates: { travel: 0.5, dining: 0.5, online: 1, groceries: 0.5, fuel: 0.5, utility: 0.5, default: 0.5 },
    perks: [
      '2pts/₹100 base = 0.5% effective',
      '4pts/₹100 on online spends = 1% (capped 1,000pts/month)',
      '8 domestic lounge visits/yr',
      '1+1 BookMyShow movie tickets twice a month (up to ₹200)',
    ],
    bestFor: ['low_fee'],
    categories: ['online'],
    intlTravel: false,
    welcomeBonus: 3000,
    isActive: true,
    isInviteOnly: false,
  },
  {
    slug: 'rbl_world_plus',
    name: 'World Plus SuperCard',
    bank: 'RBL Bank',
    network: 'Mastercard',
    annualFee: 4999,
    feeWaiverRule: 'No spend-based waiver',
    minIncome: 60000,
    rewardRates: { travel: 0.5, dining: 5, online: 0.5, groceries: 0.5, fuel: 0.5, utility: 0.5, default: 0.5 },
    perks: [
      '20pts/₹100 on dining = 5% effective (capped ₹2,000pts/month)',
      '20pts/₹100 on international spends = 5% effective',
      '8 domestic lounge visits/yr',
      '1+1 BookMyShow tickets 2x/month (up to ₹200)',
    ],
    bestFor: ['dining'],
    categories: ['dining'],
    intlTravel: true,
    welcomeBonus: 5000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── YES Bank ─────────────────────────────────────────────────────────────
  {
    slug: 'yes_first_exclusive',
    name: 'First Exclusive',
    bank: 'YES Bank',
    network: 'Mastercard',
    annualFee: 999,
    feeWaiverRule: 'Often issued Lifetime Free',
    minIncome: 25000,
    rewardRates: { travel: 1.5, dining: 1.5, online: 1.5, groceries: 1.5, fuel: 1, utility: 1.5, default: 1.5 },
    perks: [
      '12 pts/₹200 = ~1.5% base on all eligible spends',
      'Up to 3X on accelerated categories (dining, travel)',
      'Domestic lounge access',
      'Good dining discounts through EazyDiner partnerships',
    ],
    bestFor: ['low_fee', 'cashback'],
    categories: ['dining', 'online'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Scapia / Federal Bank ────────────────────────────────────────────────
  {
    slug: 'scapia_federal',
    name: 'Scapia Federal',
    bank: 'Federal Bank (Scapia)',
    network: 'Visa',
    annualFee: 0,
    feeWaiverRule: 'Lifetime free',
    minIncome: 15000,
    rewardRates: { travel: 10, dining: 2, online: 2, groceries: 2, fuel: 0, utility: 2, default: 2 },
    perks: [
      'Lifetime free with ZERO forex markup',
      '10% Scapia Coins on travel bookings via Scapia app',
      '2% on all other spends',
      'Unlimited domestic lounge on ₹10k/month spend',
      'Great entry card for international travel',
    ],
    bestFor: ['travel_perks', 'low_fee'],
    categories: ['travel'],
    intlTravel: true,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── IndusInd Bank ────────────────────────────────────────────────────────
  {
    slug: 'indusind_eazydiner',
    name: 'EazyDiner IndusInd',
    bank: 'IndusInd Bank',
    network: 'Visa',
    annualFee: 2499,
    feeWaiverRule: 'Waived on ₹3L annual spend',
    minIncome: 50000,
    rewardRates: { travel: 1.5, dining: 8, online: 2, groceries: 1.5, fuel: 0, utility: 1.5, default: 1.5 },
    perks: [
      'Up to 25% off (max ₹1,000/visit) at partner restaurants via EazyDiner PayEazy',
      'Best dining card in India for restaurant spends',
      '4 domestic lounge visits/qtr',
      '2% on online spends',
      'Complimentary EazyDiner Prime membership',
    ],
    bestFor: ['dining'],
    categories: ['dining'],
    intlTravel: false,
    welcomeBonus: 2499,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── AU Small Finance Bank ────────────────────────────────────────────────
  {
    slug: 'au_lit',
    name: 'LIT Credit Card',
    bank: 'AU Small Finance Bank',
    network: 'Visa',
    annualFee: 499,
    feeWaiverRule: 'Waived on ₹1L annual spend',
    minIncome: 15000,
    rewardRates: { travel: 1, dining: 2, online: 2, groceries: 1, fuel: 1, utility: 1, default: 1 },
    perks: [
      "India's first customizable credit card — pick features you want",
      'Activate/deactivate lounge, OTT, insurance benefits as needed',
      '2% on dining and online spends',
      'Good entry-level card for younger users',
    ],
    bestFor: ['low_fee', 'cashback'],
    categories: ['online', 'dining'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── HDFC MoneyBack+ ──────────────────────────────────────────────────────
  {
    slug: 'hdfc_moneyback_plus',
    name: 'MoneyBack+',
    bank: 'HDFC Bank',
    network: 'Visa',
    annualFee: 500,
    feeWaiverRule: 'Waived on ₹50k annual spend',
    minIncome: 20000,
    rewardRates: { travel: 0.33, dining: 0.33, online: 1.67, groceries: 0.33, fuel: 0, utility: 0.33, default: 0.33 },
    perks: [
      '10X CashPoints on Amazon, Flipkart, BigBasket, Swiggy, Reliance Smart (cap 2,500 pts/mo)',
      '2 CashPoints per ₹150 on all other spends = 0.33%',
      '₹500 gift voucher on ₹50k quarterly spend milestone',
      '10% Swiggy Dineout + 15% off at 2,000+ restaurants',
    ],
    bestFor: ['cashback', 'online', 'low_fee'],
    categories: ['online'],
    intlTravel: false,
    welcomeBonus: 500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── SBI SimplySAVE ────────────────────────────────────────────────────────
  {
    slug: 'sbi_simplysave',
    name: 'SimplySAVE',
    bank: 'SBI Card',
    network: 'Visa',
    annualFee: 499,
    feeWaiverRule: 'Waived on ₹1L annual spend',
    minIncome: 20000,
    rewardRates: { travel: 0.17, dining: 1.67, online: 0.17, groceries: 1.67, fuel: 0, utility: 0.17, default: 0.17 },
    perks: [
      '10X rewards on dining, groceries, movies & dept stores = 1.67% value',
      '1 RP per ₹150 on all other spends = 0.17%',
      '2,000 bonus points on ₹2k spend in first 60 days',
      '1% fuel surcharge waiver (₹500–₹3,000 txns)',
    ],
    bestFor: ['low_fee', 'cashback'],
    categories: ['dining', 'groceries'],
    intlTravel: false,
    welcomeBonus: 500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── OneCard (Federal Bank) ────────────────────────────────────────────────
  {
    slug: 'onecard_federal',
    name: 'OneCard',
    bank: 'Federal Bank',
    network: 'Visa',
    annualFee: 0,
    feeWaiverRule: 'Lifetime free — FD-backed option available',
    minIncome: 0,
    rewardRates: { travel: 2, dining: 2, online: 2, groceries: 2, fuel: 0, utility: 0.4, default: 0.4 },
    perks: [
      '5X reward points on top 2 spend categories each month (~2% value)',
      '1 RP per ₹50 base = 0.4% on all other spends',
      'Need 3+ category spends and ₹750 min per category for 5X eligibility',
      '1% forex markup — among lowest in India',
      'Metal card, fully app-managed, no income proof needed for FD-backed',
    ],
    bestFor: ['low_fee', 'cashback'],
    categories: ['online', 'dining'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── IDFC First Classic ───────────────────────────────────────────────────
  {
    slug: 'idfc_first_classic',
    name: 'First Classic',
    bank: 'IDFC First Bank',
    network: 'Visa',
    annualFee: 0,
    feeWaiverRule: 'Lifetime free — no annual fee ever',
    minIncome: 15000,
    rewardRates: { travel: 1, dining: 1, online: 1.5, groceries: 1, fuel: 0, utility: 0.5, default: 0.5 },
    perks: [
      'Lifetime free with no annual fee',
      '6 RP per ₹150 on online = ~1.5% · 3 RP per ₹150 offline = ~0.5%',
      '10X on spends above ₹20k/month and on birthday',
      '4 railway lounge visits per quarter (₹20k prev-month spend)',
      'Fuel surcharge waiver up to ₹200/month',
    ],
    bestFor: ['low_fee'],
    categories: ['online'],
    intlTravel: false,
    welcomeBonus: 500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Airtel Axis Bank ─────────────────────────────────────────────────────
  {
    slug: 'axis_airtel',
    name: 'Airtel Axis Bank',
    bank: 'Axis Bank',
    network: 'Visa',
    annualFee: 500,
    feeWaiverRule: 'Waived on ₹2L annual spend',
    minIncome: 25000,
    rewardRates: { travel: 1, dining: 10, online: 1, groceries: 10, fuel: 0, utility: 10, default: 1 },
    perks: [
      '25% cashback on Airtel bills via Airtel Thanks app (cap ₹250/mo)',
      '10% on utilities via Airtel Thanks (cap ₹250/mo)',
      '10% on Zomato, Swiggy, BigBasket (combined cap ₹500/mo)',
      '1% uncapped on all other spends',
      '4 domestic lounge visits/yr on ₹50k quarterly spend',
    ],
    bestFor: ['cashback'],
    categories: ['utility', 'dining', 'groceries'],
    intlTravel: false,
    welcomeBonus: 500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── HDFC Tata Neu Plus ───────────────────────────────────────────────────
  {
    slug: 'hdfc_tata_neu_plus',
    name: 'Tata Neu Plus',
    bank: 'HDFC Bank',
    network: 'Visa',
    annualFee: 499,
    feeWaiverRule: 'Waived on ₹1L annual spend',
    minIncome: 25000,
    rewardRates: { travel: 2, dining: 1, online: 7, groceries: 2, fuel: 0, utility: 1, default: 1 },
    perks: [
      'Up to 7% NeuCoins on Tata Neu App (incl. 5% NeuPass bonus)',
      '2% on Tata partner brands (BigBasket, Croma, Air India, Westside)',
      '1% on all other non-Tata spends',
      '4 domestic lounge visits/yr (1/qtr, milestone-based from June 2025)',
      'NeuCoins = ₹1 each, redeemable on Tata Neu App',
    ],
    bestFor: ['cashback', 'online'],
    categories: ['online', 'groceries'],
    intlTravel: false,
    welcomeBonus: 499,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── YES PaisaSave ────────────────────────────────────────────────────────
  {
    slug: 'yes_paisasave',
    name: 'PaisaSave',
    bank: 'YES Bank',
    network: 'Visa',
    annualFee: 499,
    feeWaiverRule: 'Waived on ₹1.2L annual spend; zero joining fee',
    minIncome: 25000,
    rewardRates: { travel: 6, dining: 6, online: 1, groceries: 1, fuel: 0, utility: 1, default: 1 },
    perks: [
      '6% cashback on dining and travel (cap ₹3,000/month)',
      '1% unlimited cashback on all other spends',
      'No merchant restrictions for accelerated cashback',
      'Virtual RuPay variant for UPI credit payments',
      '1% fuel surcharge waiver (₹500–₹3,000 txns)',
    ],
    bestFor: ['cashback', 'dining'],
    categories: ['dining', 'travel'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── HDFC Bharat Cashback ─────────────────────────────────────────────────
  {
    slug: 'hdfc_bharat_cashback',
    name: 'Bharat Cashback',
    bank: 'HDFC Bank',
    network: 'RuPay',
    annualFee: 500,
    feeWaiverRule: 'Waived on ₹50k annual spend',
    minIncome: 10000,
    rewardRates: { travel: 5, dining: 0, online: 0, groceries: 5, fuel: 5, utility: 5, default: 0 },
    perks: [
      '5% cashback on IRCTC, groceries, bill payments, mobile recharges, fuel (cap ₹150/mo combined)',
      '5% on PayZapp/EasyEMI/SmartBuy (cap ₹150/mo)',
      'Max ₹300/month = ₹3,600/year savings',
      '1% fuel surcharge waiver (₹400+ txns, cap ₹250/cycle)',
      'Great for low-income utility/fuel users',
    ],
    bestFor: ['cashback', 'low_fee'],
    categories: ['fuel', 'utility', 'groceries'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── HDFC Marriott Bonvoy ─────────────────────────────────────────────────
  {
    slug: 'hdfc_marriott_bonvoy',
    name: 'Marriott Bonvoy',
    bank: 'HDFC Bank',
    network: 'Visa',
    annualFee: 3000,
    feeWaiverRule: 'No spend-based waiver',
    minIncome: 50000,
    rewardRates: { travel: 2.67, dining: 2.67, online: 1.33, groceries: 1.33, fuel: 0, utility: 1.33, default: 1.33 },
    perks: [
      '8 Marriott points per ₹150 at Marriott hotels (~2.67%)',
      '4 points per ₹150 on travel, dining, entertainment (~1.33%)',
      '2 points per ₹150 on all other spends (~0.67%)',
      'Free Night Award on joining + up to 3 more on milestones',
      'Marriott Silver Elite status + 10 Elite Night Credits/yr',
      '12 domestic + 12 intl lounge visits/yr',
    ],
    bestFor: ['travel_perks', 'rewards_points'],
    categories: ['travel', 'dining'],
    intlTravel: true,
    welcomeBonus: 3000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Air India SBI Signature ──────────────────────────────────────────────
  {
    slug: 'sbi_air_india_signature',
    name: 'Air India SBI Signature',
    bank: 'SBI Card',
    network: 'Visa',
    annualFee: 4999,
    feeWaiverRule: 'No spend-based waiver',
    minIncome: 100000,
    rewardRates: { travel: 10, dining: 4, online: 4, groceries: 4, fuel: 0, utility: 4, default: 4 },
    perks: [
      '10 RP per ₹100 on Air India bookings (reduced from 30 in Mar 2025)',
      '4 RP per ₹100 on all other spends',
      '20,000 welcome bonus points + Flying Returns membership',
      '8 domestic Visa lounges/yr + Priority Pass membership',
      'Up to 1L bonus points on ₹5L/₹10L/₹20L annual spend milestones',
    ],
    bestFor: ['travel_perks'],
    categories: ['travel'],
    intlTravel: true,
    welcomeBonus: 4999,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── HSBC TravelOne ───────────────────────────────────────────────────────
  {
    slug: 'hsbc_travelone',
    name: 'TravelOne',
    bank: 'HSBC Bank',
    network: 'Mastercard',
    annualFee: 4999,
    feeWaiverRule: 'Waived on ₹8L annual spend',
    minIncome: 50000,
    rewardRates: { travel: 4, dining: 2, online: 2, groceries: 2, fuel: 0, utility: 0, default: 2 },
    perks: [
      '4 RP per ₹100 on flights, travel aggregators, forex (cap 50k pts/mo)',
      '2 RP per ₹100 on all other spends — uncapped',
      '1:1 transfer to 15+ airline & hotel partners',
      '6 domestic + 4 intl lounge visits/yr',
      '15% off on Yatra, Cleartrip, EaseMyTrip, Paytm',
    ],
    bestFor: ['travel_perks', 'rewards_points'],
    categories: ['travel'],
    intlTravel: true,
    welcomeBonus: 4999,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── SBI IRCTC Platinum ───────────────────────────────────────────────────
  {
    slug: 'sbi_irctc_platinum',
    name: 'IRCTC SBI Platinum',
    bank: 'SBI Card',
    network: 'Visa',
    annualFee: 500,
    feeWaiverRule: 'Renewal fee ₹300 from year 2',
    minIncome: 20000,
    rewardRates: { travel: 10, dining: 0.8, online: 0.8, groceries: 0.8, fuel: 0, utility: 0.8, default: 0.8 },
    perks: [
      'Up to 10% value back on AC1/AC2/AC3/Chair Car via IRCTC',
      '1 RP per ₹125 on all other retail spends = 0.8%',
      '1% transaction charge waiver on IRCTC bookings',
      '4 railway lounge visits/yr (1/qtr)',
      'Best card for frequent train travelers',
    ],
    bestFor: ['travel_perks', 'low_fee'],
    categories: ['travel'],
    intlTravel: false,
    welcomeBonus: 350,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Axis Horizon ─────────────────────────────────────────────────────────
  {
    slug: 'axis_horizon',
    name: 'Horizon',
    bank: 'Axis Bank',
    network: 'Visa',
    annualFee: 3000,
    feeWaiverRule: 'No spend-based waiver — 1,500 EDGE Miles renewal bonus instead',
    minIncome: 50000,
    rewardRates: { travel: 5, dining: 2, online: 2, groceries: 2, fuel: 0, utility: 0, default: 2 },
    perks: [
      '5 EDGE Miles per ₹100 on TravelEDGE portal + airlines',
      '2 EDGE Miles per ₹100 on all other spends',
      '1:1 transfer to 15+ airline & hotel partners',
      '32 domestic + 8 intl lounge visits/yr',
      '5,000 EDGE Miles welcome bonus on ₹1k first txn in 30 days',
    ],
    bestFor: ['travel_perks'],
    categories: ['travel'],
    intlTravel: true,
    welcomeBonus: 5000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── ICICI HPCL Coral ─────────────────────────────────────────────────────
  {
    slug: 'icici_hpcl_coral',
    name: 'HPCL Coral',
    bank: 'ICICI Bank',
    network: 'Visa',
    annualFee: 199,
    feeWaiverRule: 'Waived on ₹50k annual spend',
    minIncome: 20000,
    rewardRates: { travel: 0.5, dining: 0.5, online: 0.5, groceries: 0.25, fuel: 3.5, utility: 0.25, default: 0.5 },
    perks: [
      '2.5% cashback on HPCL fuel (cap ₹100/mo) + 1% surcharge waiver = 3.5% total',
      '2 PAYBACK points per ₹100 on general retail = ~0.5%',
      '15% off at 800+ partner restaurants',
      '₹100 off on 2 BookMyShow tickets/month',
      '2 domestic lounge visits/quarter',
    ],
    bestFor: ['low_fee'],
    categories: ['fuel'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── BPCL SBI Octane ──────────────────────────────────────────────────────
  {
    slug: 'sbi_bpcl_octane',
    name: 'BPCL SBI Octane',
    bank: 'SBI Card',
    network: 'Visa',
    annualFee: 1499,
    feeWaiverRule: 'Waived on ₹2L annual spend',
    minIncome: 30000,
    rewardRates: { travel: 0.25, dining: 2.5, online: 0.25, groceries: 2.5, fuel: 7.25, utility: 0.25, default: 0.25 },
    perks: [
      '6.25% value back on BPCL fuel (25 RP/₹100, cap 2500/cycle) + 1% surcharge waiver = 7.25%',
      '10 RP per ₹100 on dining, movies, groceries = 2.5%',
      '1 RP per ₹100 on all other spends = 0.25%',
      '4 domestic Visa lounge visits/yr (1/qtr)',
      '₹2k e-voucher on ₹3L annual spend milestone',
    ],
    bestFor: ['cashback'],
    categories: ['fuel'],
    intlTravel: false,
    welcomeBonus: 1500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── IDFC First Power+ ───────────────────────────────────────────────────
  {
    slug: 'idfc_first_power',
    name: 'First Power+',
    bank: 'IDFC First Bank',
    network: 'Visa',
    annualFee: 499,
    feeWaiverRule: 'Lifetime free option available; waived on ₹1.5L spend',
    minIncome: 15000,
    rewardRates: { travel: 0.5, dining: 0.5, online: 0.5, groceries: 5, fuel: 5, utility: 5, default: 0.5 },
    perks: [
      '5% savings on HPCL fuel (30 RP/₹150, cap 2400/cycle)',
      '5% on grocery and utility bills (cap 400 RP/cycle)',
      '5% on IDFC FIRST FASTag recharges (cap 200 RP/cycle)',
      '3X reward points on all other retail spends',
      '₹500 welcome bonus on first HPCL fuel transaction',
    ],
    bestFor: ['low_fee'],
    categories: ['fuel', 'utility', 'groceries'],
    intlTravel: false,
    welcomeBonus: 500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── ICICI Rubyx ──────────────────────────────────────────────────────────
  {
    slug: 'icici_rubyx',
    name: 'Rubyx',
    bank: 'ICICI Bank',
    network: 'Mastercard',
    annualFee: 3000,
    feeWaiverRule: 'Renewal ₹2,000; waived on ₹3L annual spend',
    minIncome: 50000,
    rewardRates: { travel: 2, dining: 2, online: 2, groceries: 2, fuel: 0, utility: 1, default: 2 },
    perks: [
      '2 RP per ₹100 on domestic spends · 4 RP on international = 2–4%',
      'Dual card — Mastercard + American Express networks',
      '25% off on BookMyShow/Inox (cap ₹150, 2x/month each)',
      '2 domestic lounge visits/qtr on ₹75k prev-qtr spend',
      'Up to 2 complimentary golf rounds/month',
      'Over ₹5k in welcome vouchers (Tata CliQ, EaseMyTrip, Uber, Croma)',
    ],
    bestFor: ['rewards_points'],
    categories: ['online', 'dining', 'travel'],
    intlTravel: true,
    welcomeBonus: 5000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── IDFC First Millenia ──────────────────────────────────────────────────
  {
    slug: 'idfc_first_millenia',
    name: 'First Millenia',
    bank: 'IDFC First Bank',
    network: 'Visa',
    annualFee: 0,
    feeWaiverRule: 'Lifetime free — no annual fee ever',
    minIncome: 15000,
    rewardRates: { travel: 1.5, dining: 1.5, online: 1.5, groceries: 0.5, fuel: 0, utility: 0.25, default: 0.5 },
    perks: [
      'Lifetime free — truly no annual fee',
      '6X on online spends (up to ₹20k/mo) = ~1.5% · 3X offline = ~0.5%',
      '10X on spends above ₹20k/month and on birthday',
      'Reward points never expire',
      '4 railway lounge visits/quarter (₹20k prev-month spend)',
      '25% off movie tickets once/month via District/Paytm (cap ₹100)',
    ],
    bestFor: ['low_fee', 'online'],
    categories: ['online'],
    intlTravel: false,
    welcomeBonus: 500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Axis Insta Easy ──────────────────────────────────────────────────────
  {
    slug: 'axis_insta_easy',
    name: 'Insta Easy',
    bank: 'Axis Bank',
    network: 'Visa',
    annualFee: 0,
    feeWaiverRule: 'Lifetime free — secured against FD',
    minIncome: 0,
    rewardRates: { travel: 1, dining: 1, online: 1, groceries: 1, fuel: 0, utility: 1, default: 1 },
    perks: [
      'Secured card against Fixed Deposit — no income proof needed',
      '1% cashback on all spends',
      'Perfect for building credit history from scratch',
      'Limit from ₹20k to 80% of FD value',
      'FD earns interest while card provides credit access',
    ],
    bestFor: ['low_fee'],
    categories: ['online'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── HDFC Diners Club Privilege ───────────────────────────────────────────
  {
    slug: 'hdfc_diners_privilege',
    name: 'Diners Club Privilege',
    bank: 'HDFC Bank',
    network: 'Diners',
    annualFee: 1000,
    feeWaiverRule: 'Waived on ₹3L annual spend',
    minIncome: 60000,
    rewardRates: { travel: 1.33, dining: 3.33, online: 1.33, groceries: 1.33, fuel: 0, utility: 1.33, default: 1.33 },
    perks: [
      '4 pts/₹150 base = 1.33% (1pt=₹0.50 via SmartBuy travel)',
      '5X on Swiggy/Zomato food delivery · up to 10X on SmartBuy (cap 4k pts/mo)',
      'BOGO BookMyShow weekend movie tickets (cap ₹250, 2 free/month)',
      'Swiggy One + Times Prime membership on ₹75k spend in 90 days',
      '2 domestic lounge visits/qtr on ₹15k prev-qtr spend',
    ],
    bestFor: ['rewards_points', 'dining'],
    categories: ['dining', 'online'],
    intlTravel: false,
    welcomeBonus: 1000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── SBI IRCTC Premier ────────────────────────────────────────────────────
  {
    slug: 'sbi_irctc_premier',
    name: 'IRCTC SBI Premier',
    bank: 'SBI Card',
    network: 'Visa',
    annualFee: 1499,
    feeWaiverRule: 'Waived on ₹2L annual spend',
    minIncome: 30000,
    rewardRates: { travel: 10, dining: 2.4, online: 0.8, groceries: 0.8, fuel: 0, utility: 2.4, default: 0.8 },
    perks: [
      '10% value back on IRCTC AC/Chair Car bookings',
      '5% on air tickets and e-catering via IRCTC',
      '3 RP/₹125 on dining + utility = ~2.4%',
      '8 railway lounge visits/yr (2/qtr)',
      '1% transaction charge waiver on IRCTC bookings',
      '7,500 bonus points on ₹1L annual travel spend milestone',
    ],
    bestFor: ['travel_perks'],
    categories: ['travel'],
    intlTravel: false,
    welcomeBonus: 1500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── SBI Miles Elite ──────────────────────────────────────────────────────
  {
    slug: 'sbi_miles_elite',
    name: 'Miles Elite',
    bank: 'SBI Card',
    network: 'Visa',
    annualFee: 4999,
    feeWaiverRule: 'Waived on ₹15L annual spend',
    minIncome: 150000,
    rewardRates: { travel: 3, dining: 1, online: 1, groceries: 1, fuel: 0, utility: 0, default: 1 },
    perks: [
      '6 Travel Credits/₹200 on flights, hotels, travel agencies = 3%',
      '2 Travel Credits/₹200 on all other spends = 1%',
      '1:1 transfer to Air Canada, British Airways, Cathay Pacific, Accor, Shangri-La + more',
      '5,000 welcome Travel Credits on ₹1L spend in 60 days',
      '20,000 bonus credits on ₹12L annual spend milestone',
    ],
    bestFor: ['travel_perks', 'rewards_points'],
    categories: ['travel'],
    intlTravel: true,
    welcomeBonus: 5000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── SBI Prime ────────────────────────────────────────────────────────────
  {
    slug: 'sbi_prime',
    name: 'Prime',
    bank: 'SBI Card',
    network: 'Visa',
    annualFee: 2999,
    feeWaiverRule: 'Waived on ₹3L annual spend',
    minIncome: 80000,
    rewardRates: { travel: 0.5, dining: 2.5, online: 0.5, groceries: 2.5, fuel: 0, utility: 5, default: 0.5 },
    perks: [
      '10 RP/₹100 on dining, groceries, dept stores, movies = 2.5%',
      '20 RP/₹100 on utility bills via standing instructions = 5%',
      '8 domestic + 4 intl Priority Pass lounge visits/yr',
      '₹3k welcome e-voucher on annual fee payment',
      '₹1k Pizza Hut voucher on ₹50k quarterly spend milestone',
    ],
    bestFor: ['travel_perks', 'dining'],
    categories: ['dining', 'groceries', 'utility'],
    intlTravel: true,
    welcomeBonus: 3000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Axis Select ──────────────────────────────────────────────────────────
  {
    slug: 'axis_select',
    name: 'Select',
    bank: 'Axis Bank',
    network: 'Visa',
    annualFee: 3000,
    feeWaiverRule: 'Waived on ₹8L annual spend; free for Burgundy customers',
    minIncome: 150000,
    rewardRates: { travel: 1, dining: 1, online: 2, groceries: 2, fuel: 0, utility: 0, default: 1 },
    perks: [
      '2% (20 EDGE pts/₹200) on shopping — apparel, grocery, dept stores (cap ₹20k/mo)',
      '1% (10 EDGE pts/₹200) on all other eligible spends',
      '8 domestic + up to 12 intl lounge visits/yr via Priority Pass',
      '10,000 welcome EDGE pts (₹2k value) on first txn in 30 days',
      '5,000 milestone pts on ₹3L annual spend',
    ],
    bestFor: ['travel_perks', 'rewards_points'],
    categories: ['online', 'groceries', 'travel'],
    intlTravel: true,
    welcomeBonus: 2000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── ICICI Coral ──────────────────────────────────────────────────────────
  {
    slug: 'icici_coral',
    name: 'Coral',
    bank: 'ICICI Bank',
    network: 'Visa',
    annualFee: 500,
    feeWaiverRule: 'Waived on ₹1.5L annual spend',
    minIncome: 20000,
    rewardRates: { travel: 0.5, dining: 0.5, online: 0.5, groceries: 0.5, fuel: 0, utility: 0.25, default: 0.5 },
    perks: [
      '2 RP per ₹100 on retail spends = 0.5%',
      '25% off on BookMyShow/Inox (cap ₹100, 2x/month)',
      '1 domestic lounge visit/qtr on ₹75k prev-qtr spend',
      '4 railway lounge visits/yr',
      '2,000 bonus points at ₹2L annual spend milestone',
      '15–20% off at partner restaurants via Culinary Treats',
    ],
    bestFor: ['low_fee'],
    categories: ['online', 'dining'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── HSBC Premier ─────────────────────────────────────────────────────────
  {
    slug: 'hsbc_premier',
    name: 'Premier',
    bank: 'HSBC Bank',
    network: 'Mastercard',
    annualFee: 0,
    feeWaiverRule: 'Free for HSBC Premier banking customers',
    minIncome: 300000,
    rewardRates: { travel: 3, dining: 3, online: 3, groceries: 3, fuel: 0, utility: 0, default: 3 },
    perks: [
      '3 RP per ₹100 on all eligible spends = 3% (1pt=₹1 for miles/hotel transfers)',
      '1:1 transfer to 20+ airline & hotel partners',
      'Unlimited domestic + intl lounge access (LoungeKey)',
      '8 guest lounge visits/yr at international lounges',
      '0.99% forex markup — among lowest in India',
      'Points never expire',
    ],
    bestFor: ['travel_perks', 'rewards_points'],
    categories: ['travel', 'dining', 'online'],
    intlTravel: true,
    welcomeBonus: 20000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Kotak IndianOil ──────────────────────────────────────────────────────
  {
    slug: 'kotak_indianoil',
    name: 'IndianOil',
    bank: 'Kotak Mahindra Bank',
    network: 'Visa',
    annualFee: 449,
    feeWaiverRule: 'Waived on ₹50k annual spend',
    minIncome: 20000,
    rewardRates: { travel: 0.5, dining: 2, online: 0.5, groceries: 2, fuel: 4, utility: 0.5, default: 0.5 },
    perks: [
      '4% value back on IndianOil fuel (24 RP/₹150, cap 1200/cycle) + 1% surcharge waiver = 5% total',
      '2% on groceries and dining (12 RP/₹150, cap 800/cycle)',
      '0.5% on all other spends (3 RP/₹150)',
      '1,000 welcome bonus points on ₹500 first-month spend',
      'Available in RuPay variant for UPI payments',
    ],
    bestFor: ['low_fee'],
    categories: ['fuel', 'groceries', 'dining'],
    intlTravel: false,
    welcomeBonus: 250,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Kotak White ──────────────────────────────────────────────────────────
  {
    slug: 'kotak_white',
    name: 'White',
    bank: 'Kotak Mahindra Bank',
    network: 'Visa',
    annualFee: 3000,
    feeWaiverRule: 'Waived on ₹5L annual spend',
    minIncome: 100000,
    rewardRates: { travel: 2.25, dining: 2.25, online: 2.25, groceries: 2.25, fuel: 0, utility: 0, default: 2.25 },
    perks: [
      'White Pass Value system — earn up to ₹27,000/yr in vouchers',
      'Effective 1–2.25% reward rate depending on spend level',
      '8 domestic + 4 intl lounge visits/yr via Priority Pass',
      '₹1,500 voucher on ₹30k spend in first 60 days',
      '1% fuel surcharge waiver (₹400–₹7,500 txns)',
    ],
    bestFor: ['rewards_points', 'travel_perks'],
    categories: ['travel', 'online', 'dining'],
    intlTravel: true,
    welcomeBonus: 1500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── RBL Popcorn ──────────────────────────────────────────────────────────
  {
    slug: 'rbl_popcorn',
    name: 'Popcorn',
    bank: 'RBL Bank',
    network: 'Mastercard',
    annualFee: 1000,
    feeWaiverRule: 'No spend-based waiver',
    minIncome: 25000,
    rewardRates: { travel: 0, dining: 0, online: 0, groceries: 0, fuel: 0, utility: 0, default: 0 },
    perks: [
      '2 free movie tickets/month on BookMyShow (₹5k min monthly spend)',
      '₹25 assured cashback every week on ₹2,500+ weekly spend',
      '₹1,000 BookMyShow welcome vouchers (2x ₹500)',
      '1% fuel surcharge waiver (cap ₹100/month)',
      'Best card for movie lovers',
    ],
    bestFor: ['low_fee'],
    categories: ['dining'],
    intlTravel: false,
    welcomeBonus: 1000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── RBL Shoprite ─────────────────────────────────────────────────────────
  {
    slug: 'rbl_shoprite',
    name: 'Shoprite',
    bank: 'RBL Bank',
    network: 'Mastercard',
    annualFee: 500,
    feeWaiverRule: 'Waived on ₹1–1.5L annual spend',
    minIncome: 20000,
    rewardRates: { travel: 0.25, dining: 0.25, online: 0.25, groceries: 5, fuel: 0, utility: 0.25, default: 0.25 },
    perks: [
      '5% value back on grocery supermarket spends (20 RP/₹100, cap 1000 pts/mo)',
      '1 RP per ₹100 on all other spends = 0.25%',
      '2,000 welcome bonus points on first txn + joining fee payment',
      '10% off on BookMyShow (cap ₹100, 15x/yr)',
      'Best entry card for grocery-first households',
    ],
    bestFor: ['cashback', 'low_fee'],
    categories: ['groceries'],
    intlTravel: false,
    welcomeBonus: 500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── IndusInd Legend ──────────────────────────────────────────────────────
  {
    slug: 'indusind_legend',
    name: 'Legend',
    bank: 'IndusInd Bank',
    network: 'Visa',
    annualFee: 0,
    feeWaiverRule: 'Lifetime free (one-time joining fee may apply)',
    minIncome: 50000,
    rewardRates: { travel: 1, dining: 1, online: 1.5, groceries: 1, fuel: 0, utility: 0.5, default: 1 },
    perks: [
      '2X rewards on weekends (Sat-Sun) · 1X on weekdays',
      '1 RP = ₹0.50 cash / ₹0.75 non-cash / 1:1 airline miles',
      'BOGO BookMyShow tickets (₹200 cap/month)',
      '1.8% forex markup — lower than industry standard',
      'Priority Pass membership + travel insurance up to ₹25L',
      '3,000–4,000 bonus points on ₹5L–₹6L annual spend',
    ],
    bestFor: ['low_fee', 'travel_perks'],
    categories: ['online', 'travel'],
    intlTravel: true,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── IndusInd Tiger ───────────────────────────────────────────────────────
  {
    slug: 'indusind_tiger',
    name: 'Tiger',
    bank: 'IndusInd Bank',
    network: 'Visa',
    annualFee: 0,
    feeWaiverRule: 'Lifetime free',
    minIncome: 25000,
    rewardRates: { travel: 1, dining: 1, online: 1, groceries: 1, fuel: 0, utility: 0, default: 1 },
    perks: [
      'Tiered rewards: 1RP/₹100 up to ₹1L → 2RP up to ₹2.5L → 4RP up to ₹5L → 6RP above ₹5L',
      'Up to 7.2% effective on high annual spends',
      '1.5% forex markup — among best LTF cards for international use',
      '8 domestic + 2 intl lounge visits/yr via Priority Pass',
      'Lifetime free — truly no annual fee',
    ],
    bestFor: ['low_fee', 'travel_perks'],
    categories: ['travel', 'online'],
    intlTravel: true,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── BOBCARD Eterna ───────────────────────────────────────────────────────
  {
    slug: 'bobcard_eterna',
    name: 'Eterna',
    bank: 'Bank of Baroda',
    network: 'Visa',
    annualFee: 2499,
    feeWaiverRule: 'Lifetime Free offer for applications until Mar 2026; otherwise waived on ₹2.5L',
    minIncome: 60000,
    rewardRates: { travel: 3.75, dining: 3.75, online: 3.75, groceries: 0.75, fuel: 0, utility: 0.75, default: 0.75 },
    perks: [
      '15 RP/₹100 on online, travel, dining, intl, movies = 3.75%',
      '3 RP/₹100 on all other spends = 0.75%',
      'Unlimited domestic airport lounge access (₹40k prev-qtr spend)',
      '10,000 bonus points on ₹50k spend in first 60 days',
      '20,000 bonus points on ₹5L annual spend milestone',
      'Currently available as Lifetime Free — apply before Mar 2026',
    ],
    bestFor: ['rewards_points', 'travel_perks'],
    categories: ['online', 'travel', 'dining'],
    intlTravel: true,
    welcomeBonus: 2500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── BOBCARD Premier ──────────────────────────────────────────────────────
  {
    slug: 'bobcard_premier',
    name: 'Premier',
    bank: 'Bank of Baroda',
    network: 'Visa',
    annualFee: 1000,
    feeWaiverRule: 'Waived on ₹1.2L annual spend; LTF offer available until Mar 2026',
    minIncome: 30000,
    rewardRates: { travel: 2.5, dining: 2.5, online: 0.5, groceries: 0.5, fuel: 0, utility: 0.5, default: 0.5 },
    perks: [
      '5X rewards on travel, dining, intl spends = 2.5% (cap 2000 pts/cycle)',
      '2 RP/₹100 on all other spends = 0.5%',
      '1 domestic lounge visit/qtr (₹20k prev-qtr spend from Jan 2025)',
      '500 bonus points on ₹5k first-60-days spend',
      '1% fuel surcharge waiver (₹400–₹5,000 txns)',
    ],
    bestFor: ['low_fee'],
    categories: ['travel', 'dining'],
    intlTravel: false,
    welcomeBonus: 500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── AU Bank Zenith ───────────────────────────────────────────────────────
  {
    slug: 'au_zenith',
    name: 'Zenith',
    bank: 'AU Small Finance Bank',
    network: 'Visa',
    annualFee: 7999,
    feeWaiverRule: 'Joining waived on ₹1.25L in 90 days; renewal waived on ₹5L annual spend',
    minIncome: 100000,
    rewardRates: { travel: 2.5, dining: 5, online: 1.25, groceries: 2.5, fuel: 0, utility: 0.25, default: 1.25 },
    perks: [
      '5% on dining (20 RP/₹100) · 2.5% on groceries + intl (10 RP/₹100)',
      '1.25% on all other eligible spends (5 RP/₹100)',
      '8 domestic + 8 intl lounge visits/yr (2/qtr each)',
      '10,000 bonus points on ₹1L spend in first 60 days',
      'Epicure membership on ₹8L annual spend',
    ],
    bestFor: ['dining', 'travel_perks'],
    categories: ['dining', 'groceries', 'travel'],
    intlTravel: true,
    welcomeBonus: 2500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── AU Bank Zenith+ ─────────────────────────────────────────────────────
  {
    slug: 'au_zenith_plus',
    name: 'Zenith+',
    bank: 'AU Small Finance Bank',
    network: 'Visa',
    annualFee: 4999,
    feeWaiverRule: 'Renewal waived on ₹8L annual spend',
    minIncome: 150000,
    rewardRates: { travel: 2, dining: 2, online: 1, groceries: 1, fuel: 0, utility: 0, default: 1 },
    perks: [
      '2 RP per ₹100 on dining, intl, travel (1pt = ₹1) = 2%',
      '1 RP per ₹100 on all other spends = 1%',
      '0.99% forex markup — among lowest in India (metal card)',
      '1,000 bonus points/month on ₹75k monthly spend',
      '5,000 renewal bonus points from year 2',
    ],
    bestFor: ['travel_perks'],
    categories: ['travel', 'dining'],
    intlTravel: true,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── AU Bank Altura Plus ──────────────────────────────────────────────────
  {
    slug: 'au_altura_plus',
    name: 'Altura Plus',
    bank: 'AU Small Finance Bank',
    network: 'Visa',
    annualFee: 499,
    feeWaiverRule: 'Yr 1 waived on ₹20k in 90 days; renewal on ₹80k annual spend',
    minIncome: 25000,
    rewardRates: { travel: 0.5, dining: 0.5, online: 0.5, groceries: 0.5, fuel: 0, utility: 0.25, default: 1.5 },
    perks: [
      '1.5% cashback on all POS retail spends (cap ₹100/cycle)',
      '2X reward points on online spends',
      '500 bonus points on ₹20k monthly retail spend milestone',
      '1% fuel surcharge waiver',
      'Good entry-level cashback card',
    ],
    bestFor: ['cashback', 'low_fee'],
    categories: ['online'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── HDFC Business MoneyBack ──────────────────────────────────────────────
  {
    slug: 'hdfc_business_moneyback',
    name: 'Business MoneyBack',
    bank: 'HDFC Bank',
    network: 'Visa',
    annualFee: 500,
    feeWaiverRule: 'Waived on ₹50k annual spend',
    minIncome: 0,
    rewardRates: { travel: 0.33, dining: 0.33, online: 2, groceries: 0.33, fuel: 0, utility: 0.33, default: 0.33 },
    perks: [
      '10X CashPoints on business/online spends at select merchants = ~2%',
      '2 CashPoints/₹150 on all other spends = 0.33%',
      'Designed for sole proprietors and small businesses (ITR ₹6L+)',
      'Quarterly milestone vouchers on ₹50k spend',
      '1% fuel surcharge waiver',
    ],
    bestFor: ['cashback', 'online'],
    categories: ['online'],
    intlTravel: false,
    welcomeBonus: 500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── IDFC FIRST WOW ──────────────────────────────────────────────────────
  {
    slug: 'idfc_first_wow',
    name: 'FIRST WOW',
    bank: 'IDFC First Bank',
    network: 'Visa',
    annualFee: 0,
    feeWaiverRule: 'Lifetime free — secured against FD',
    minIncome: 0,
    rewardRates: { travel: 1, dining: 1, online: 1, groceries: 1, fuel: 0, utility: 0.25, default: 1 },
    perks: [
      'FD-backed — credit limit = 100% of FD value, no income proof needed',
      '0% forex markup — zero foreign currency charges',
      '4X reward points on all spends (1pt = ₹0.25) = ~1%',
      'Unlimited reward points that never expire',
      'FD continues to earn 6.25% interest while card is active',
      'Best secured card for zero-history + international travel',
    ],
    bestFor: ['low_fee', 'travel_perks'],
    categories: ['travel', 'online'],
    intlTravel: true,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Fibe Axis Bank ───────────────────────────────────────────────────────
  {
    slug: 'axis_fibe',
    name: 'Fibe Axis Bank',
    bank: 'Axis Bank',
    network: 'RuPay',
    annualFee: 0,
    feeWaiverRule: 'Lifetime free — zero joining and annual fees',
    minIncome: 0,
    rewardRates: { travel: 1, dining: 3, online: 3, groceries: 1, fuel: 0, utility: 0, default: 1 },
    perks: [
      'Up to 3% cashback on food delivery, entertainment, local commute (cap ₹1,500/cycle)',
      '1% cashback on all other spends',
      'India\'s first numberless credit card (card details in Fibe app)',
      '4 domestic lounge visits/yr',
      'UPI-compatible RuPay card — link to any UPI app',
      '15% off at 10,000+ restaurants via Axis Dining Delights',
    ],
    bestFor: ['low_fee', 'cashback'],
    categories: ['dining', 'online'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── IDFC FIRST WOW! Black ────────────────────────────────────────────────
  {
    slug: 'idfc_first_wow_black',
    name: 'FIRST WOW! Black',
    bank: 'IDFC First Bank',
    network: 'Mastercard',
    annualFee: 750,
    feeWaiverRule: 'Waived on ₹1.5L annual spend; FD-backed (₹20k min FD)',
    minIncome: 0,
    rewardRates: { travel: 10, dining: 1, online: 1, groceries: 1, fuel: 0, utility: 0.25, default: 1 },
    perks: [
      '50 bonus RP/₹150 on hotel bookings via IDFC app = ~16.7% value',
      '30 bonus RP/₹150 on flight bookings via IDFC app = ~10% value',
      '4X RP on all other online/offline/intl spends = ~1%',
      '0% forex markup — zero foreign currency charges',
      '4 domestic lounge visits/yr',
      'FD-backed card — 100% of FD as credit limit, FD earns interest',
      'Trip cancellation cover up to ₹10k (2x/yr)',
    ],
    bestFor: ['travel_perks', 'low_fee'],
    categories: ['travel', 'online'],
    intlTravel: true,
    welcomeBonus: 5000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── MagniFi (Federal Bank × AU) ──────────────────────────────────────────
  {
    slug: 'magnifi_federal',
    name: 'MagniFi',
    bank: 'Federal Bank',
    network: 'Visa',
    annualFee: 0,
    feeWaiverRule: 'Lifetime free — no joining or annual fees',
    minIncome: 25000,
    rewardRates: { travel: 5, dining: 5, online: 0.5, groceries: 5, fuel: 0, utility: 0, default: 0.5 },
    perks: [
      '5% cashback on eligible weekend spends (dining, shopping, travel, cabs, groceries)',
      '0.5% cashback on weekday spends',
      '20% instant discounts on weekends via Amazon, Zomato, Zepto, BookMyShow (capped)',
      'Rewards in Fi-Points (4 pts = ₹1) — redeem for cash, miles, or vouchers',
      'Co-branded by Fi × Federal Bank × AU Small Finance Bank',
    ],
    bestFor: ['cashback', 'low_fee'],
    categories: ['dining', 'groceries', 'travel'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Standard Chartered EaseMyTrip ─────────────────────────────────────────
  {
    slug: 'sc_easemytrip',
    name: 'EaseMyTrip',
    bank: 'Standard Chartered',
    network: 'Visa',
    annualFee: 350,
    feeWaiverRule: 'Waived on ₹50k annual spend',
    minIncome: 20000,
    rewardRates: { travel: 2.5, dining: 0.5, online: 0.5, groceries: 0.5, fuel: 0, utility: 0, default: 0.5 },
    perks: [
      '10 RP/₹100 on direct airline/hotel website bookings = 2.5%',
      '2 RP/₹100 on all other spends = 0.5%',
      '20% off on EaseMyTrip hotels (cap ₹5k domestic, ₹10k intl)',
      '10% off on EaseMyTrip flights (cap ₹1k domestic, ₹5k intl)',
      '1 domestic + 2 intl lounge visits/yr',
      'Uncapped reward points — no monthly limits',
    ],
    bestFor: ['travel_perks', 'low_fee'],
    categories: ['travel'],
    intlTravel: true,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── IndusInd Avios Visa Infinite ──────────────────────────────────────────
  {
    slug: 'indusind_avios',
    name: 'Avios Visa Infinite',
    bank: 'IndusInd Bank',
    network: 'Visa',
    annualFee: 10000,
    feeWaiverRule: 'Renewal ₹5,000; no spend-based waiver',
    minIncome: 150000,
    rewardRates: { travel: 3, dining: 1.5, online: 1.5, groceries: 1.5, fuel: 0, utility: 0.5, default: 1.5 },
    perks: [
      '6 Avios/₹200 at preferred intl destination (POS) · 5 Avios on BA/Qatar direct bookings',
      '3 Avios/₹200 on all other spends',
      '20,000 welcome Avios + up to 36,000 milestone Avios/yr (at ₹8L + ₹16L)',
      'Choice of BA Executive Club or Qatar Privilege Club (potential Gold status)',
      '8 domestic + 8 intl lounge visits/yr (2/qtr via Priority Pass)',
      '1.5% forex markup at preferred destination (vs 3.5% standard)',
    ],
    bestFor: ['travel_perks', 'rewards_points'],
    categories: ['travel'],
    intlTravel: true,
    welcomeBonus: 20000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Amex SmartEarn ───────────────────────────────────────────────────────
  {
    slug: 'amex_smartearn',
    name: 'SmartEarn',
    bank: 'American Express',
    network: 'Amex',
    annualFee: 495,
    feeWaiverRule: 'Waived on ₹40k annual spend',
    minIncome: 37500,
    rewardRates: { travel: 2, dining: 2, online: 2, groceries: 1, fuel: 0, utility: 0, default: 1 },
    perks: [
      '10X MR on Zomato, EaseMyTrip, Flipkart, Uber, Myntra, BookMyShow, Ajio, Nykaa (cap 500+500 pts/mo)',
      '5X on Amazon (cap 250 pts/mo)',
      '1 MR per ₹50 on all other spends = ~1%',
      '₹500 cashback on ₹10k spend in first 90 days',
      '₹500 vouchers on ₹1.2L/₹1.8L/₹2.4L annual milestones (up to ₹1,500)',
    ],
    bestFor: ['cashback', 'online'],
    categories: ['online', 'dining'],
    intlTravel: false,
    welcomeBonus: 500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Amex Membership Rewards (MRCC) ───────────────────────────────────────
  {
    slug: 'amex_mrcc',
    name: 'Membership Rewards',
    bank: 'American Express',
    network: 'Amex',
    annualFee: 1000,
    feeWaiverRule: 'Renewal ₹4,500; waived on ₹1.5L annual spend',
    minIncome: 50000,
    rewardRates: { travel: 2, dining: 2, online: 2, groceries: 2, fuel: 0, utility: 0, default: 2 },
    perks: [
      '1 MR/₹50 base = ~2% (via 24K Gold Collection: Taj ₹14k, Tanishq ₹9k, Amazon ₹8k for 24k pts)',
      '1,000 bonus pts/mo on 4 txns of ₹1,500+ · 1,000 more on ₹20k/mo',
      '5X via Reward Multiplier portal on 100+ brands',
      '18K/24K Gold Collection — premium voucher redemptions',
      'Up to ~6% effective reward rate when milestones are met consistently',
    ],
    bestFor: ['rewards_points'],
    categories: ['dining', 'online', 'travel'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Amex Platinum Reserve ─────────────────────────────────────────────────
  {
    slug: 'amex_platinum_reserve',
    name: 'Platinum Reserve',
    bank: 'American Express',
    network: 'Amex',
    annualFee: 10000,
    feeWaiverRule: 'Waived on ₹10L annual spend',
    minIncome: 200000,
    rewardRates: { travel: 2, dining: 2, online: 2, groceries: 2, fuel: 0, utility: 0, default: 2 },
    perks: [
      '1 MR/₹50 = ~2% base · up to 5X via RewardXcelerator',
      '₹1k voucher/mo on ₹50k monthly spend = ₹12k/yr',
      'Complimentary Taj Epicure Plus — 25% off dining + 20% off rooms at Taj hotels',
      '12 domestic + 2 intl lounge visits/yr via Priority Pass',
      '2 free golf rounds/month at top courses across India',
      'EazyDiner Prime membership included',
    ],
    bestFor: ['travel_perks', 'rewards_points', 'dining'],
    categories: ['travel', 'dining', 'online'],
    intlTravel: true,
    welcomeBonus: 10000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Axis Neo ─────────────────────────────────────────────────────────────
  {
    slug: 'axis_neo',
    name: 'Neo',
    bank: 'Axis Bank',
    network: 'Visa',
    annualFee: 250,
    feeWaiverRule: 'LTF eligible — often issued free',
    minIncome: 15000,
    rewardRates: { travel: 0.1, dining: 0.1, online: 0.1, groceries: 0.1, fuel: 0, utility: 0, default: 0.1 },
    perks: [
      '₹120 off Zomato (min ₹499) — 2x per month',
      '10% off movie tickets on BookMyShow (cap ₹100/mo)',
      '10% off on Blinkit (cap ₹250, min ₹750) monthly',
      '₹150 off on Myntra (min ₹999)',
      '5% off utility bills via Paytm (cap ₹150/mo)',
      '15% off at partner restaurants via Axis Dining Delights',
      'Best entry card for direct merchant discounts',
    ],
    bestFor: ['low_fee'],
    categories: ['dining', 'online'],
    intlTravel: false,
    welcomeBonus: 300,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Axis Rewards ─────────────────────────────────────────────────────────
  {
    slug: 'axis_rewards',
    name: 'Rewards',
    bank: 'Axis Bank',
    network: 'Visa',
    annualFee: 1000,
    feeWaiverRule: 'Waived on ₹2L annual spend',
    minIncome: 25000,
    rewardRates: { travel: 0.3, dining: 0.3, online: 3.3, groceries: 0.3, fuel: 0, utility: 0, default: 0.3 },
    perks: [
      '10X EDGE pts on apparel + dept stores = 3.3% (cap ₹7k/mo spend)',
      '2 EDGE pts/₹125 on all other spends = 0.3%',
      '30% off Swiggy food delivery (cap ₹150, min ₹200) — 2x/mo',
      '2 domestic lounge visits/qtr (₹50k prev-3mo spend)',
      '5,000 welcome EDGE points on ₹1k first-30-days spend',
      '1,500 bonus pts on ₹30k single-cycle spend',
    ],
    bestFor: ['rewards_points', 'online'],
    categories: ['online', 'dining'],
    intlTravel: false,
    welcomeBonus: 1000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── ICICI Emeralde Private Metal ─────────────────────────────────────────
  {
    slug: 'icici_emeralde_private',
    name: 'Emeralde Private Metal',
    bank: 'ICICI Bank',
    network: 'Visa',
    annualFee: 12499,
    feeWaiverRule: 'Waived on ₹10L annual spend; invite-only',
    minIncome: 300000,
    rewardRates: { travel: 18, dining: 3, online: 3, groceries: 3, fuel: 0, utility: 0, default: 3 },
    perks: [
      '3% base (6 pts/₹200, 1pt = ₹1) on all retail spends',
      '6X on flights via iShop = ~18% · 12X on hotels via iShop = ~36% (cap 18k bonus pts/mo)',
      'Unlimited domestic + intl lounge access',
      'Complimentary Taj Epicure + EazyDiner Prime membership',
      'Unlimited golf rounds/lessons at premium courses',
      '2% forex markup · ₹10k joining fee includes luxury welcome kit',
    ],
    bestFor: ['travel_perks', 'rewards_points', 'dining'],
    categories: ['travel', 'dining', 'online'],
    intlTravel: true,
    welcomeBonus: 12499,
    isActive: true,
    isInviteOnly: true,
  },

  // ─── SBI KrisFlyer ────────────────────────────────────────────────────────
  {
    slug: 'sbi_krisflyer',
    name: 'KrisFlyer SBI',
    bank: 'SBI Card',
    network: 'Visa',
    annualFee: 2999,
    feeWaiverRule: 'No spend-based waiver',
    minIncome: 60000,
    rewardRates: { travel: 2.5, dining: 1, online: 1, groceries: 1, fuel: 0, utility: 0, default: 1 },
    perks: [
      '5 KF miles/₹200 on Singapore Airlines Group + intl spends = 2.5%',
      '2 KF miles/₹200 on all other spends = 1%',
      '3,000 KF miles welcome bonus on fee payment + first txn in 60 days',
      'Upgrade to KrisFlyer Elite Silver on ₹2.5L SIA spend',
      '3,000 bonus miles on ₹3L annual spend milestone',
      'Domestic + intl lounge access included',
    ],
    bestFor: ['travel_perks', 'rewards_points'],
    categories: ['travel'],
    intlTravel: true,
    welcomeBonus: 3000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── IndusInd Duo ─────────────────────────────────────────────────────────
  {
    slug: 'indusind_duo',
    name: 'Duo',
    bank: 'IndusInd Bank',
    network: 'Visa',
    annualFee: 0,
    feeWaiverRule: 'Lifetime free (₹249 joining fee may apply)',
    minIncome: 20000,
    rewardRates: { travel: 0.67, dining: 0.67, online: 0.67, groceries: 0.67, fuel: 0, utility: 0, default: 0.67 },
    perks: [
      'India\'s first debit-cum-credit card (dual EMV chips)',
      '1 RP/₹150 on all spends — no expiry on credit card points',
      'BOGO movie tickets on BookMyShow (12x/yr, cap ₹250)',
      '20% off on Zomato + BigBasket',
      '2% cross-currency markup waiver for intl transactions',
      'Travel insurance: ₹25L air accident + ₹1L lost baggage + ₹50k lost passport',
      'Up to 8 lounge visits/yr',
    ],
    bestFor: ['low_fee'],
    categories: ['dining', 'online'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── RBL Bank Play ────────────────────────────────────────────────────────
  {
    slug: 'rbl_play',
    name: 'Play',
    bank: 'RBL Bank',
    network: 'Mastercard',
    annualFee: 500,
    feeWaiverRule: 'Waived on ₹1.5L annual spend',
    minIncome: 20000,
    rewardRates: { travel: 0, dining: 0, online: 0, groceries: 0, fuel: 0, utility: 0, default: 0 },
    perks: [
      '₹500 BookMyShow discount/mo on ₹5k monthly billing spend (2 free tickets, cap ₹250 each)',
      '10% effective savings on entertainment when threshold met',
      '₹100 off food & beverages on BookMyShow movie bookings',
      '₹500 welcome BookMyShow discount on first purchase in 30 days',
      '1% fuel surcharge waiver (₹500–₹4,000)',
      'Best card for movie/event/stream enthusiasts (BookMyShow co-brand)',
    ],
    bestFor: ['low_fee'],
    categories: ['dining'],
    intlTravel: false,
    welcomeBonus: 500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── DBS Vantage (Treasures) ──────────────────────────────────────────────
  {
    slug: 'dbs_vantage',
    name: 'Vantage',
    bank: 'DBS Bank',
    network: 'Visa',
    annualFee: 10000,
    feeWaiverRule: 'Free for Treasures Elite customers; ₹20k for Treasures; waived on ₹10L',
    minIncome: 300000,
    rewardRates: { travel: 4, dining: 2, online: 2, groceries: 2, fuel: 0, utility: 0, default: 2 },
    perks: [
      '4 VP/₹200 domestic = 2% · 8 VP/₹200 intl = 4% (1 VP = ₹1)',
      'Unlimited domestic + intl lounge access (Priority Pass 10 visits/yr)',
      'Transfer points to Air India Maharaja Miles (5 VP → 4 miles)',
      '10,000 welcome VPs on first txn in 30 days',
      '5,000/10,000/40,000 bonus VPs on ₹3L/₹5L/₹20L quarterly/annual milestones',
      'Welcome Taj Epicure or ITC Culinaire or Club Marriott membership',
    ],
    bestFor: ['travel_perks', 'rewards_points'],
    categories: ['travel', 'dining', 'online'],
    intlTravel: true,
    welcomeBonus: 10000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── DBS Spark ────────────────────────────────────────────────────────────
  {
    slug: 'dbs_spark',
    name: 'Spark',
    bank: 'DBS Bank',
    network: 'Visa',
    annualFee: 999,
    feeWaiverRule: 'Spark5 ₹499 / Spark10 ₹999 (waived ₹2L) / Spark20 ₹1,499 (waived ₹2.5L)',
    minIncome: 25000,
    rewardRates: { travel: 0.2, dining: 0.2, online: 2, groceries: 0.2, fuel: 0, utility: 0, default: 0.2 },
    perks: [
      '2 CashPoints/₹200 base (0.2%) · up to 20X on online spends after ₹15k–₹20k monthly threshold',
      'Milestone: up to 7,000 bonus CashPoints/mo + 5,000/qtr on Spark20',
      'BOGO BookMyShow tickets (cap ₹200 on second ticket)',
      '1–2 domestic lounge visits/qtr (Spark10/20 only)',
      '1% fuel surcharge waiver (cap ₹150–₹200/mo)',
      '3 variants for different spend levels — entry-level DBS card',
    ],
    bestFor: ['low_fee', 'online'],
    categories: ['online'],
    intlTravel: false,
    welcomeBonus: 5000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── YES Bank Marquee ─────────────────────────────────────────────────────
  {
    slug: 'yes_marquee',
    name: 'Marquee',
    bank: 'YES Bank',
    network: 'Visa',
    annualFee: 9999,
    feeWaiverRule: 'Renewal ₹4,999; waived on ₹10L annual spend',
    minIncome: 200000,
    rewardRates: { travel: 2.25, dining: 2.25, online: 4.5, groceries: 2.25, fuel: 0, utility: 1.25, default: 2.25 },
    perks: [
      '36 YES Rewardz/₹200 on online = 4.5% · 18 pts/₹200 offline = 2.25%',
      'Unlimited intl lounge access + 24 domestic lounge visits/yr (6/qtr)',
      '8 guest lounge visits/yr (domestic or intl)',
      '1% forex markup — among lowest in India',
      'BOGO BookMyShow tickets',
      'Cap: 1L pts/statement cycle',
    ],
    bestFor: ['rewards_points', 'travel_perks'],
    categories: ['online', 'travel', 'dining'],
    intlTravel: true,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── YES Bank Reserv ──────────────────────────────────────────────────────
  {
    slug: 'yes_reserv',
    name: 'Reserv',
    bank: 'YES Bank',
    network: 'Visa',
    annualFee: 2499,
    feeWaiverRule: 'Waived on ₹3L annual spend; first-yr waived on ₹40k in 30 days',
    minIncome: 80000,
    rewardRates: { travel: 1.5, dining: 1.5, online: 3, groceries: 1.5, fuel: 0, utility: 0.75, default: 1.5 },
    perks: [
      '24 YES Rewardz/₹200 on online = 3% · 12 pts/₹200 offline = 1.5%',
      '3 domestic + 6 intl lounge visits/yr',
      '1.75% forex markup',
      'BOGO BookMyShow tickets',
      'Complimentary golf lessons + rounds at select courses',
      'Purchase protection + baggage delay cover',
    ],
    bestFor: ['rewards_points', 'travel_perks'],
    categories: ['online', 'travel'],
    intlTravel: true,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── HSBC Visa Platinum ───────────────────────────────────────────────────
  {
    slug: 'hsbc_visa_platinum',
    name: 'Visa Platinum',
    bank: 'HSBC Bank',
    network: 'Visa',
    annualFee: 0,
    feeWaiverRule: 'Lifetime free — no joining or annual fees',
    minIncome: 30000,
    rewardRates: { travel: 4, dining: 0.66, online: 0.66, groceries: 0.66, fuel: 0, utility: 0.66, default: 0.66 },
    perks: [
      '2 RP/₹150 base = 0.66% · 6X on Travel with Points portal = ~4%',
      '1:1 transfer to 15 airlines (BA, SQ, Qatar, Air India, Etihad, JAL, United) + 5 hotels (Marriott, Accor, IHG, Shangri-La, Wyndham)',
      '5X on annual spends above ₹4L (cap 15k accelerated pts/yr)',
      'BOGO BookMyShow on Saturdays',
      'Best LTF card for airline/hotel mile transfers in India',
    ],
    bestFor: ['low_fee', 'travel_perks', 'rewards_points'],
    categories: ['travel'],
    intlTravel: true,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── HSBC Taj ─────────────────────────────────────────────────────────────
  {
    slug: 'hsbc_taj',
    name: 'Taj',
    bank: 'HSBC Bank',
    network: 'Visa',
    annualFee: 110000,
    feeWaiverRule: 'No waiver — ₹1,10,000 + GST annually',
    minIncome: 0,
    rewardRates: { travel: 5, dining: 5, online: 1, groceries: 1, fuel: 0, utility: 0, default: 1 },
    perks: [
      '5 pts/₹100 at Taj/Vivanta/SeleQtions = ~5% (3.3% redeemed) + 8 Neu Coins = ~11% total',
      '1.5 pts/₹100 on all other spends = ~1%',
      '0% forex markup on international transactions',
      'Unlimited domestic + intl lounge access',
      'Taj InnerCircle Platinum NeuPass membership included',
      'Welcome: 1-night Taj Palace stay + 2 nights at any 5-star IHCL hotel',
      '₹1Cr air accidental cover · The Chambers Lounge access 12x/yr',
    ],
    bestFor: ['travel_perks', 'dining'],
    categories: ['travel', 'dining'],
    intlTravel: true,
    welcomeBonus: 110000,
    isActive: true,
    isInviteOnly: true,
  },

  // ─── HDFC BizBlack Metal ──────────────────────────────────────────────────
  {
    slug: 'hdfc_bizblack',
    name: 'BizBlack Metal',
    bank: 'HDFC Bank',
    network: 'Visa',
    annualFee: 10000,
    feeWaiverRule: 'Joining waived on ₹1.5L in 90 days; renewal on ₹7.5L annual spend',
    minIncome: 0,
    rewardRates: { travel: 3.33, dining: 3.33, online: 3.33, groceries: 3.33, fuel: 0, utility: 3.33, default: 3.33 },
    perks: [
      '5 pts/₹150 base = 3.33% (1pt = ₹1) · 10X on SmartBuy hotels · 5X on tax/GST/insurance via PayZapp',
      'Unlimited domestic + intl lounge access for primary + add-on',
      '6 golf games/qtr at premier courses globally',
      'Business insurance package (fire, burglary, equipment, hospital cash)',
      'Club Marriott + ₹5k Taj vouchers on ₹1.5L welcome spend',
      '₹5k voucher per ₹5L retail milestone (up to ₹20k/yr)',
      'Designed for self-employed/businesses (ITR ₹30L+ required)',
    ],
    bestFor: ['rewards_points', 'travel_perks'],
    categories: ['online', 'travel', 'dining'],
    intlTravel: true,
    welcomeBonus: 5000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Axis Reserve ─────────────────────────────────────────────────────────
  {
    slug: 'axis_reserve',
    name: 'Reserve',
    bank: 'Axis Bank',
    network: 'Visa',
    annualFee: 50000,
    feeWaiverRule: 'Waived on ₹35L annual spend',
    minIncome: 0,
    rewardRates: { travel: 1.5, dining: 1.5, online: 1.5, groceries: 1.5, fuel: 0, utility: 0, default: 1.5 },
    perks: [
      '15 EDGE pts/₹200 domestic = 1.5% · 2X intl (30 pts/₹200) = 3%',
      'Unlimited domestic + intl lounge (12 guest visits/yr)',
      '50 free golf rounds/yr at premium courses',
      'Luxury airport transfers (chauffeur-driven)',
      'ITC Culinaire + AccorPlus + Club Marriott Asia Pacific memberships',
      '50,000 welcome EDGE pts on activation + renewal',
      'Ultra-premium metal card — India\'s most exclusive open-market card',
    ],
    bestFor: ['travel_perks', 'rewards_points'],
    categories: ['travel', 'dining', 'online'],
    intlTravel: true,
    welcomeBonus: 50000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Kotak PVR INOX ──────────────────────────────────────────────────────
  {
    slug: 'kotak_pvr_inox',
    name: 'PVR INOX',
    bank: 'Kotak Mahindra Bank',
    network: 'Visa',
    annualFee: 499,
    feeWaiverRule: 'No spend-based waiver (₹499/yr)',
    minIncome: 20000,
    rewardRates: { travel: 0, dining: 0, online: 0, groceries: 0, fuel: 0, utility: 0, default: 0 },
    perks: [
      '1 free PVR INOX ticket (up to ₹300) per ₹10k monthly spend — unlimited tickets',
      '5% flat discount on PVR INOX movie tickets',
      '20% off food & beverages at PVR INOX cinemas',
      'PVR INOX in-cinema lounge access',
      '1% fuel surcharge waiver',
      'Best card in India for dedicated movie lovers',
    ],
    bestFor: ['low_fee'],
    categories: ['dining'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── SBI PULSE ────────────────────────────────────────────────────────────
  {
    slug: 'sbi_pulse',
    name: 'PULSE',
    bank: 'SBI Card',
    network: 'Visa',
    annualFee: 1499,
    feeWaiverRule: 'Waived on ₹2L annual spend',
    minIncome: 50000,
    rewardRates: { travel: 2, dining: 10, online: 2, groceries: 2, fuel: 0, utility: 2, default: 2 },
    perks: [
      '10 RP/₹100 on dining, pharma, sports, movies = 2.5%',
      '2 RP/₹100 on all other spends = 0.5%',
      'Welcome: Noise ColorFit Pulse smartwatch (worth ~₹5k) on joining fee payment',
      'Complimentary 1-yr FITPASS PRO (12 gym sessions/mo + nutritionist)',
      'Complimentary 1-yr Netmeds First (free consultations + delivery)',
      '8 domestic lounge visits/yr (2/qtr) + Priority Pass membership',
      '₹1,500 Netmeds voucher on ₹4L annual spend milestone',
      '₹50L air accident cover + baggage loss insurance',
    ],
    bestFor: ['rewards_points'],
    categories: ['dining', 'online'],
    intlTravel: false,
    welcomeBonus: 5000,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── ICICI Platinum Chip ──────────────────────────────────────────────────
  {
    slug: 'icici_platinum',
    name: 'Platinum Chip',
    bank: 'ICICI Bank',
    network: 'Visa',
    annualFee: 0,
    feeWaiverRule: 'Lifetime free — no joining or annual fees',
    minIncome: 0,
    rewardRates: { travel: 2, dining: 2, online: 2, groceries: 2, fuel: 0, utility: 1, default: 2 },
    perks: [
      '2 PAYBACK pts/₹100 on retail = ~2% via iShop redemption',
      '1 pt/₹100 on insurance + utility spends',
      'Up to 6X–12X via iShop portal on flights, hotels, vouchers',
      '15% off dining via ICICI Culinary Treats programme',
      '1% fuel surcharge waiver (₹400–₹4k at HPCL)',
      'Best zero-fee card for credit building — no income proof required',
    ],
    bestFor: ['low_fee'],
    categories: ['dining', 'online'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Slice (SBM Bank) ────────────────────────────────────────────────────
  {
    slug: 'slice_sbm',
    name: 'Slice',
    bank: 'SBM Bank India',
    network: 'Visa',
    annualFee: 0,
    feeWaiverRule: 'Lifetime free — no joining or annual fees',
    minIncome: 0,
    rewardRates: { travel: 2, dining: 2, online: 3, groceries: 2, fuel: 0, utility: 0, default: 2 },
    perks: [
      'Up to 3% cashback on all spends (via "monies" / fires)',
      'Pay-in-3: split any purchase into 3 interest-free monthly payments',
      'Instant approval — card issued in minutes via Slice app',
      'UPI-linked credit card — works with all UPI apps',
      'Real-time spend tracking + smart insights in app',
      'No income proof required — popular with students and Gen Z',
    ],
    bestFor: ['low_fee', 'cashback'],
    categories: ['online', 'dining'],
    intlTravel: false,
    welcomeBonus: 0,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── HDFC Freedom ─────────────────────────────────────────────────────────
  {
    slug: 'hdfc_freedom',
    name: 'Freedom',
    bank: 'HDFC Bank',
    network: 'Visa',
    annualFee: 500,
    feeWaiverRule: 'Waived on ₹50k annual spend',
    minIncome: 18000,
    rewardRates: { travel: 0.1, dining: 0.1, online: 1, groceries: 0.1, fuel: 0, utility: 0, default: 0.1 },
    perks: [
      '10X CashPoints on BigBasket, BookMyShow, OYO, Swiggy, Uber (cap 2,500 pts/mo)',
      '1 CashPoint/₹150 on all other spends including UPI = 0.1%',
      '10X on PayZapp + SmartBuy purchases',
      '20% off dining via Swiggy Dineout + 10% with code HDFCCARDS',
      '25X reward points on birthday spends (cap 3,000 pts)',
      '₹1k gift voucher on ₹90k annual spend milestone',
      'One of HDFC\'s most issued entry cards — high approval rate',
    ],
    bestFor: ['low_fee'],
    categories: ['online', 'dining'],
    intlTravel: false,
    welcomeBonus: 500,
    isActive: true,
    isInviteOnly: false,
  },

  // ─── Bajaj Finserv DBS SuperCard ──────────────────────────────────────────
  {
    slug: 'bajaj_dbs_supercard',
    name: 'SuperCard',
    bank: 'DBS Bank',
    network: 'Visa',
    annualFee: 599,
    feeWaiverRule: '3 variants: ₹599 (5X) / ₹999 (7X) / ₹1,499 (10X); waiver rules vary',
    minIncome: 25000,
    rewardRates: { travel: 1, dining: 1, online: 2, groceries: 1, fuel: 0, utility: 0, default: 1 },
    perks: [
      'Up to 10X Cash Points via DBS Card+ IN app on eligible spends',
      '5X/7X/10X multiplier on spends above ₹10k–₹20k/mo (variant-dependent)',
      '2 CashPoints/₹200 base on all retail spends',
      '5% cashback on No-Cost EMI down payments at Bajaj Finserv stores (cap ₹500)',
      'No-Cost EMI conversion on large purchases',
      '1–2 domestic lounge visits/qtr (higher variants)',
      'Built on Bajaj Finserv ecosystem — millions of existing EMI card users migrated',
    ],
    bestFor: ['cashback', 'online'],
    categories: ['online'],
    intlTravel: false,
    welcomeBonus: 2000,
    isActive: true,
    isInviteOnly: false,
  },
];

async function main() {
  console.log('Seeding card database...');
  let upserted = 0;

  for (const card of CARDS) {
    await prisma.card.upsert({
      where: { slug: card.slug },
      update: card,
      create: card,
    });
    upserted++;
  }

  console.log(`Done. Upserted ${upserted} cards.`);
}

main()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
